### ISSUE TITLE
Minor mbtiles summary improvements

### ISSUE THREAD

**Issue by nyurik** [urbica/martin#1002]
The new `mbtiles summary` tool could have a bit of cleanup:

* [ ] Move all summary code from `mbtiles/src/mbtiles.rs` to `mbtiles/src/summary.rs`
* [ ] Use one of the pretty table printers to display the output. See [available crates](https://crates.io/search?q=category%3Acommand-line-interface%20format%20table&sort=recent-downloads).

The table printer is a bit of a tricky one - at first i was thinking of using [prettytable-rs](https://crates.io/crates/prettytable-rs) or [cli-table](https://crates.io/crates/cli-table) or something similar, but then I saw [termimad](https://crates.io/crates/termimad) -- which is a markdown renderer.  In theory, that could prove a much better approach (data will be represented as markdown internally, and can be rendered as either text or pretty-printed).  So some research is needed.

**Comment by sharkAndshark** [comment]
Working on.
