### ISSUE TITLE
Cannot use config file if DATABASE_URL env var is set.

### ISSUE THREAD

**Issue by p-rutledge** [urbica/martin#1050]
I know what you are going to say, "don't set DATABASE_URL".

However I am deploying to a digital ocean app (their platform as a service). And they automatically set an environment variable of DATABASE_URL.

Basically, what I am requesting, is a way to use the config (for me, I want to configure the tables and functions accessible to martin) while the DATABASE_URL env var exists.
Maybe we add a way to ignore the DATABASE_URL environment variable; be it with a flag or an entry in the config file, or some other creative way.
Or maybe you fine fine developers have other ideas on an implementation.

Anyway, hopefully you all agree that this is worth fixing, or augmenting. 

Thanks a bunch, 
Patrick

**Comment by nyurik** [comment]
> I know what you are going to say, "don't set DATABASE_URL".

:rofl: I won't say that. It is a valid concern / use case.  I see three use cases

* Use all env vars even if `--config` param is used. (currently default)
* Disable all env vars, e.g. with `--no-env` param.  This seems good, except that we have to decide what to do with config files as described [here](https://maplibre.org/martin/config-file.html) -- a config file may use env vars like `connection_string: ${MY_DATABASE_URL:-postgresql://postgres@localhost/db}`.  Should these still work?
* Disable all env vars completely.

Perhaps we should have a `--env-vars (off|config|on)` to cover all 3 cases?  E.g. don't use them, use them in config files only, or always use them?

Lastly, there are some env vars that are common to all of Rust programs, like `RUST_LOG` -- it changes the level of verbosity of `martin` and other tools.  Should those always be allowed regardless of the setting?

**Comment by p-rutledge** [comment]
> Perhaps we should have a --env-vars (off|config|on) to cover all 3 cases? E.g. don't use them, use them in config files only, or always use them?

I think it is important to allow env vars to be passed to the config.

> Lastly, there are some env vars that are common to all of Rust programs, like RUST_LOG -- it changes the level of verbosity of martin and other tools. Should those always be allowed regardless of the setting?

That seems reasonable. I could see the env var override pertaining to only martin env vars.
On that note, should we follow the pattern established by rust and prepend martin to our env vars? I could see that causing problems with migrations though.

Perhaps an on conflict strategy? ie. setting the dominent source if two competing sources declare the same setting.

**Comment by nyurik** [comment]
Well, we could officially stop supporting env vars...

**Comment by p-rutledge** [comment]
That works for me for settings.
However I still think it is great to allow the config file to use env vars.

**Comment by nyurik** [comment]
I agree that the config file should continue supporting them, and I am ok to remove the support for all auto-env vars (except for `RUST_LOG`?  And possibly add `--log` param?  But that's TBD separatelly)

So in order for this to happen,  we need to:
* Ensure ALL [env vars](https://maplibre.org/martin/env-vars.html) can be set at least with the config file, or best -- with both config file and CLI parameters. (I think they already are, but double check)
* Detect if any of [these env vars](https://maplibre.org/martin/env-vars.html) are set, and if they are, show a warning with clear instructions on doing it with either CLI parameters or with config (or both, or a link to docs).  For the `DATABASE_URL`, suggest to use `martin "$DATABASE_URL"` instead, or use it in a config file.
* Remove any magical handling of the env vars from the code
* Update documentation

Do you want to tackle this? Should be fairly easy and straightforward :)

**Comment by p-rutledge** [comment]
I have zero rust experience and a very busy December, but I can try and putt away at it. I wouldn't be able to commit to a deadline. 

At minimum I would be happy to do the documentation if someone else gets to the code. But it would be kind of fun to do. So yes, I will do it as long as there is no deadline expectation.

**Comment by nyurik** [comment]
@patrick-amuse you will need very little Rust experience for this, and I can walk you through the whole process (you can ask @sharkAndshark how thorough are my reviews :) ).  I would much rather help you than do the whole project on my own, and have just one person who understands it

**Comment by p-rutledge** [comment]
sounds good!

**Comment by nyurik** [comment]
I just created #1052 to track it.  Lets close this to avoid confusion.
