### ISSUE TITLE
How to change the `tiles` option in TileJSON

### ISSUE THREAD

**Issue by ghost** [urbica/martin#1054]
There should be a way to modify the host of tiles in the `tiles` options for a TileJSON of a specific source. 

Currently, If you have a martin server running on localhost and Nginx working as a reverse-proxy, martin specifies the `tiles` field as `["https://localhost:3000"]`. Which is not correct, and there should be a way to modify that field and to specify the domain/subdomain which points to Nginx.

**Comment by nyurik** [comment]
@Linker-123 the tiles value is modified with `x-rewrite-url` header. See also https://maplibre.org/martin/run-with-nginx.html#rewriting-urls

Relevant code:  https://github.com/maplibre/martin/blob/main/martin/src/srv/server.rs#L208-L213

**Comment by nyurik** [comment]
P.S. I do want to make sure this functionality works properly. If you notice that it does not work, or if the docs are wrong, we need to fix it or update the docs.

**Comment by ghost** [comment]
Hey! Thanks for pointing me to the right part of the docs. I've ended up doing it like the following:

```nginx
location / {
        proxy_set_header  X-Rewrite-URL $uri;
        proxy_set_header  X-Forwarded-Host $host;
        proxy_set_header  X-Forwarded-Proto $scheme;
        proxy_redirect    off;

        proxy_pass http://localhost:3000;
}
````
    
The example in the docs is a bit confusing, since it's trying to rewrite requests that go to `/tiles`. But that would never happen as clients would be sending requests to `https://localhost:3000`, so that might be something misleading in the docs.

**Comment by nyurik** [comment]
thx @Linker-123, would you like to make an edit suggestion of how you think that page should be fixed?  Note that clients will send the requests anywhere you send them to. So if your website uses tiles from `https://example.org/tiles/src/{z}/{x}/{y}`, then nginx would have to rewrite that URL to remove the `/tiles`.  This way you will have all other site assets located on the same server.

Markdown is [here](https://github.com/maplibre/martin/edit/main/docs/src/run-with-nginx.md)

**Comment by ghost** [comment]
Yes but, from my understanding (I'm using maplibre) that it sends requests to the provided url in `tiles` array, which martin specifies as `localhost:3000` (without the nginx config I've provided). Therefore the docs are correct but for a different thing, if martin provides an incorrect host in the tiles array, then nginx will never even receive the request. Basically just using the rewrite header fixed my issue.

**Comment by nyurik** [comment]
When configuring MapLibre, you give it the TileJSON endpoint as seen from the user's perspective.  So the user browser (maplibre) will go to some endpoint like `https://example.org/mytiles/mytilesrc`.   Nginx proxy will redirect `https://example.org/mytiles/<...>` -> `http://martin_service/<...>`, and set the `X-Rewrite-URL` header.  Martin will read that header, and set the `tiles` array correctly to `https://example.org/mytiles/mytilesrc/{z}/{x}/{y}`.  MapLibre will now try to get the tiles, and Nginx will redirect those tile requests correctly to the martin service.

Now, of course you are free to not use `mytiles` prefix, but then your Nginx will need to figure out if the request should be handled by martin or by nginx itself or by some other backend service
