### ISSUE TITLE
Make PMTiles directory cache shared between files

### ISSUE THREAD

**Issue by nyurik** [urbica/martin#1093]
Current PMTiles implementation has one directory LRU cache per file. Instead, we need:
* [x] make `PmtCache` instance shared accross all PMTiles
* [x] make it shared between both HTTP and local PMTiles files, not just HTTP ones
* [x] add `dir_cache_size` as an extra option specific to `pmtiles` config section - see #1094
* [x] limit cache size per approx memory usage https://github.com/maplibre/martin/pull/1095

**Comment by gmottajr** [comment]
Hey Yuri (@nyurik), please I need to apologize. I tried to address this issue, forked your repo and started trying to compile first. I got no success in doing that and encountered some challenges with this initiation on getting familiar with the project, and that has obstructed my progress. The time that I had to work on it just ran out. 
Anyway, I'll try to get back into this issue asap (hopefully this weekend).
If you have urgency or another person interested to work on it, please feel free to carry it on. I don't want to be the one holding you back in your project progression.

**Comment by nyurik** [comment]
@gmottajr no worries. Could you tell me what kind of issues you ran into when setting up?  I would like to make the onboarding process as simple as possible. Thx!
