### ISSUE TITLE
Fix flaky MacOS CI test, possibly using preinstalled Github's MacOS nginx instead

### ISSUE THREAD

**Issue by nyurik** [urbica/martin#1103]
It seems the nginx server in a docker container sometimes does not properly start up on macos hosts, so the `curl --head "http://localhost:5412/webp2.pmtiles"` fails to connect.

Possible solutions:
* figure out why the docker does not start, and ensure that it does
* it seems github macos runners have nginx natively (see [script](https://github.com/actions/runner-images/blob/main/images/macos/scripts/build/install-nginx.sh)) - so perhaps we can just use that, making the test faster as well?  I think this is the preferred option if possible

### Context
Initially added in https://github.com/maplibre/martin/pull/991 by @kyleslugg who knows most of the context on this one.

**Comment by kyleslugg** [comment]
Thanks for checking this out! Agreed, makes sense to use the built-in
Nginx. I’ll work on bringing it into the workflow tomorrow or Wednesday!

Kyle Slugg-Urbino

Phone: (703) 307-5551
GitHub: @kyleslugg <https://github.com/kyleslugg>
LinkedIn: @kyle-slugg <https://www.linkedin.com/in/kyle-slugg/>

**Comment by nyurik** [comment]
I fixed it in #1104, seem to be working, but ideally we should do the same with linux too - will make things more consistent. I do think we may want to create a simple github action for local serving without docker - should be fairly easy to do.
