### ISSUE TITLE
Support docker compose plugin to justfile

### ISSUE THREAD

**Issue by sharkAndshark** [urbica/martin#1149]
The [Docker compose plugin](https://docs.docker.com/compose/install/linux/) way:
```shell
docker compose up
```

The [Docker compose standalone](https://docs.docker.com/compose/install/standalone/) way:
```shell
docker-compose up
```

Is there one way to support them both? I tried many in justfile but all failed.

**Comment by nyurik** [comment]
I think we may need to test if the system has a `docker-compose`, and if it does not, use `docker compose` - something similar to the check we have in the `cargo-install` just command - but do it once when just starts up?

**Comment by nyurik** [comment]
A temporary workaround could be to add an alias to bash

**Comment by justb4** [comment]
This is a common problem, that will still remain some years, until `docker compose` is the only command.
We solved this in a workshop launch control Bash script like @nyurik indicated: sniff for the variant and set an `alias`. See [these lines](https://github.com/geopython/geopython-workshop/blob/master/workshop/geopython-workshop-ctl.sh#L14) i.e.:

```
# Sniff which Docker Compose variant is installed
# and set an alias.
# See https://github.com/geopython/geopython-workshop/issues/82
if command docker-compose --version &> /dev/null
then
  alias dockercompose='docker-compose'
  echo "Using docker-compose"
else
  if !command docker compose version &> /dev/null
  then
    echo "Neither docker-compose nor docker compose is available"
    echo "Check your Docker Installation"
    exit 1
  fi
  alias dockercompose='docker compose'  
  echo "Using docker compose"
fi

```
..and then use the alias `dockercompose`. Never heard of `just` (other than my first name..) but seems something to be added in the [justfile](https://github.com/maplibre/martin/blob/main/demo/justfile) as `bash` is presumed? Will PR...

**Comment by justb4** [comment]
The "bash-script" approach in my comment above does not really work direct in a `justfile` because of the 'just-syntax'. But figured out an alternative, using standard var and -substitution, so an approach with oneliner:

```
dockercompose := `if docker-compose --version &> /dev/null; then echo "docker-compose"; else echo "docker compose"; fi`
.
.
up:
   {{ dockercompose }} up

up-build:
    {{ dockercompose }} up --build
.
.
```
 
There is a `justfile` in the repo root and the `demo` dir. Will go ahead with this approach.
