### ISSUE TITLE
Martin v0.11.6 much faster than v0.12.0 and 0.13.0??

### ISSUE THREAD

**Issue by nyurik** [urbica/martin#1172]
### Discussed in https://github.com/maplibre/martin/discussions/1161

<div type='discussions-op-text'>

<sup>Originally posted by **radimkrchnacek** January 30, 2024</sup>
I am testing 3 different versions of Martin on localhost with the same settings (default settings, just caching disabled) and the same postgis 3.3 database table. Versions v0.12.0 and v0.13.0 seem to be much slower than v0.11.6
I also tried running Martin with `RUST_LOG=debug` and the DB queries are identical for all 3 versions.
What might be the cause of these huge performance differences?

v0.12.0:
![martin-v0 12 0](https://github.com/maplibre/martin/assets/94595399/b0f1a597-9d11-4fbf-9aca-ea5c4061406e)

v0.11.6:
![martin-v0 11 6](https://github.com/maplibre/martin/assets/94595399/a0d98e2a-c05a-4d57-8d30-00af492867d3)

v.0.13.0
![martin-v0 13 0](https://github.com/maplibre/martin/assets/94595399/30a1043d-2a7e-4fa3-aca9-b1edea9ac360)
</div>

**Comment by ShadowSonata** [comment]
I had this similar issue the other day (as I was using the tag `latest` for my testing and it automatically bumped to the latest version). I found out that the content-encoding has changed.

This is the response header in v0.11.6
<img width="925" alt="image" src="https://github.com/maplibre/martin/assets/28591411/33a87432-e6a7-4d41-beac-e0fc8fa74a44">

And the response header in v0.13.0
<img width="1009" alt="image" src="https://github.com/maplibre/martin/assets/28591411/02568adb-168d-49c0-9f5f-9fb9e0cf0f53">

If I force `content-encoding` to gzip by adding "Accept-Encoding" to my request, the response time and the data size come back to normal.
<img width="893" alt="image" src="https://github.com/maplibre/martin/assets/28591411/915626db-4c7d-4604-96fe-cc041d323225">

**Comment by nyurik** [comment]
@ShadowSonata I think that's the culprit.  I switched the default serving compression from `gzip` to `brotli` encoding (when the browser supports both and has not set a preference of one over the other).  As you can see from your own example, you gained 20% on the content size. But that 20% doesn't come from nowhere - Brotli takes longer to compress.

So there are two ways to fix this, and both in theory could be used:
* add compression preference, e.g. a CLI param `--preferred-encoding (gzip|brotli)` and a similar global config file value. If the browser does not give different `q` values for `br` and `gzip` in the [Accept-Encoding header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Encoding), Martin will pick one over the other.  By default, Chrome sets `Accept-Encoding:gzip, deflate, br` (default q=1.0 for all)
  * #1178
* Martin tile cache contains pre-compressed values - i.e. the cache has the value as returned by the tile source.  MBTiles usually stores gzipped tiles. Postgres usually returns uncompressed ones.  This means that Martin compresses tiles on each response when tiles are coming from Postgres.  The solution is to modify cache logic to store the tile after compressing it.  This will make responses much faster except for the very first one (per tile coordinates).
  * #1112

**Comment by nyurik** [comment]
The individual issues #1178 and #1112 track both of the use cases. It should be fairly easy to do - and as always, I am more than willing to guide any newcomers if someone can step forward before I get to it in my limited volunteer time. Thx!

**Comment by CommanderStorm** [comment]
> The individual issues #1178 and #1112 track both of the use cases

lets close this issue and track it in the remaining issue instead:
- #1112
