### ISSUE TITLE
Website breaks when you click on Jan 1st in the demo

### ISSUE THREAD

**Issue by StefanBrand** [urbica/martin#1193]
Clicking on Jan 1st in the demo at https://martin.maplibre.org/ breaks the website. The page turns completely blank.

Console error:

```
TypeError: this.props.range is undefined
```

Browser: Firefox 122 on Ubuntu 22.04.3

**Comment by CommanderStorm** [comment]
Issue has been resolved during https://github.com/maplibre/martin/pull/1373 and can be closed ^^

![Recording 2024-07-15 at 00 32 01](https://github.com/user-attachments/assets/30fe19a1-4706-4570-ab08-abec23bcde10)
