### ISSUE TITLE
Add a Tile Preview

### ISSUE THREAD

**Issue by rush42** [urbica/martin#1195]
It would be nice if martin served a tile preview. Right now we are hosting a `ngnix` container along with martin which only serves the [`debug.html`](https://github.com/maplibre/martin/blob/main/tests/debug.html). If martin served this by default would be quite handy.

**Comment by nyurik** [comment]
There has been a lot of interest in this - help is needed to push this forward:
* https://github.com/maplibre/martin/issues/1120 (dup of this one, so closing)
* https://github.com/maplibre/martin/pull/1142
