### ISSUE TITLE
How to handle dynamic sources?

### ISSUE THREAD

**Issue by marcelino-m** [urbica/martin#1198]
Hi,

I have some source MBTiles and PostgreSQL tables that I need to update frequently. Do you have any recommendations on how to handle this?

For example, is it possible to update a MBTiles source (patching it) without restarting the Martin server?

**Comment by nyurik** [comment]
This has been a long time requested feature #288, and @mesudBe-Orbit started working on it #1179 but I am not sure about the status

**Comment by mesudBe-Orbit** [comment]
@nyurik I am still working on it. I encountered a problem that has prompted me to delve deeper into understanding the concepts involved. Additionally, due to illness, I haven't been able to make any progress over the past week 🤒.
