### ISSUE TITLE
`Event not found` when starting martin

### ISSUE THREAD

**Issue by bernatfortet** [urbica/martin#1207]
OS: Mac
Installed via Homebrew

I just run martin with a connection string param and I'm getting `event not found`. I'm pointing at a Supabase postgres connection string so the command looks like this:
`martin postgresql://postgres:[PASSWORD]@db.[SUPABASE_ID].supabase.co:5432/postgres`
And I get this:
`event not found: [PASSWORD]@db.[SUPABASE_ID].supabase.co`

(I've intentionally removed the password and supabase ID from the above examples)

Thanks.

**Comment by nyurik** [comment]
@bernatfortet thanks for reporting! This error does not appear to be coming from Martin itself - but rather from the PostgreSQL db... Could you run it with [logging](https://maplibre.org/martin/troubleshooting.html#troubleshooting), and either post it here, or email it to me directly?  I think you have some unusual DB elements that break auto-discovery mechanism, and I would love to fix that.

**Comment by bernatfortet** [comment]
Hi @nyurik, 
I saw that my password had an `@` symbol. Something was telling me that some regex was going wrong and the auto-discovery was catching a different part of the connection string.
I changed the password and it's working now. 
Could that be it?

**Comment by nyurik** [comment]
oh wow, interesting. My guess is that the `@` symbol in the URL string must be escaped - https://superuser.com/questions/273799/how-to-use-special-characters-in-username-password-for-http-proxy
