### ISSUE TITLE
What happens when a new materialized view / table added to the database?

### ISSUE THREAD

**Issue by ozdemiri** [urbica/martin#1219]
Hey Team,

This is a very good tool. Thank you for this cool product.

I am currently utilizing the Martin tile server in conjunction with a PostgreSQL database for my project. My use case involves frequently adding new materialized views to the database, which I would like Martin to automatically detect and subsequently host tile data for these new views without requiring a manual restart of the server.

As of now, I haven't found a method within Martin's existing documentation or configuration options that supports this functionality. I have been manually restarting (with a Cron job) the Martin server to reflect changes whenever a new materialized view is added, which is not ideal for my dynamic environment.

Could you please advise if there is an existing feature or a recommended approach to achieve automatic detection and hosting of new materialized views in Martin? If not, are there any plans to include this feature in a future update? Any guidance or suggestions on how to handle this scenario would be greatly appreciated.

Thank you for your time and assistance.

**Comment by sharkAndshark** [comment]
Hi @ozdemiri  Have a good day.
This has been a long time requested feature #288, and @mesudBe-Orbit started working on it #1179
