### ISSUE TITLE
Detect old postgresql versions and warn user

### ISSUE THREAD

**Issue by nyurik** [urbica/martin#1230]
As asked in #1229, postgres 9.6 had different schema discovery structure, and yet we do not tell users that their postgresql db is too old and there might be an issue.

What we need is:
* [ ] Query Postgres version (similar to how we currently detect Postgis version)
  * There are [two ways](https://stackoverflow.com/questions/13733719/which-version-of-postgresql-am-i-running):  `select version()` good for printing as part of the `[info]` text, and `SHOW server_version` (or `SELECT current_setting('server_version')` ?) for a semver variant that can be used for testing.
* [ ] Report postgres version string to the user
* [ ] If postgres version is older than whichever version we currently support (some global const), give a warning, and note that that postgres is no longer maintained

**Comment by vatsa287** [comment]
@nyurik I am interested in working on this & get to know the codebase more. Could you please assign this to me?

**Comment by nyurik** [comment]
sure thing, thanks!
