### ISSUE TITLE
version `GLIBC_2.33' not found (required by mbtiles)

### ISSUE THREAD

**Issue by whilei** [urbica/martin#1234]
I downloaded https://github.com/maplibre/martin/releases/latest/download/martin-x86_64-unknown-linux-gnu.tar.gz (https://maplibre.org/martin/installation.html), but can't run the programs. It seems my glibc is out of date. Interaction log with errors below. 

Do I need to update, or is this expected?

I didn't find documentation about this. Upgrading glibc on my system will probably not be rainbow filled, but I'm will to try building with [an adhoc glibc](https://askubuntu.com/a/1345783/794101) if that might fix it. 

```
mbtiles validate gen/rye/points-stationary/naps.mbtiles 
mbtiles: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by mbtiles)
mbtiles: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by mbtiles)
mbtiles: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by mbtiles)

mbtiles --version
mbtiles: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by mbtiles)
mbtiles: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by mbtiles)
mbtiles: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by mbtiles)

martin --version
martin: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by martin)
martin: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by martin)
martin: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by martin)
martin: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by martin)

uname -a
Linux ubp52 5.9.16-050916-generic #202012211331 SMP Mon Dec 21 14:11:13 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by nyurik** [comment]
interesting, could you try the MUSL version?

**Comment by whilei** [comment]
Sure what's that? :joy_cat:

**Comment by nyurik** [comment]
One of the other download options on the release page

**Comment by whilei** [comment]
Oh, I see, [the _other_ Releases page](https://github.com/maplibre/martin/releases)  :) 
Thanks, that worked, I'm off and validating mbtiles. :heavy_check_mark: 
https://github.com/maplibre/martin/releases/download/v0.13.0/martin-x86_64-unknown-linux-musl.tar.gz

**Comment by nyurik** [comment]
@whilei which other release page were you using before?  Should we update the docs somewhere?  Note that the [installation instructions](https://github.com/maplibre/martin?tab=readme-ov-file#installation) also mention `musl`.

**Comment by whilei** [comment]
I was using https://maplibre.org/martin/installation.html 
![image](https://github.com/maplibre/martin/assets/10228550/3718eead-17ed-458d-adc1-44656963f011)
