### ISSUE TITLE
ghcr.io/maplibre/martin:main not found

### ISSUE THREAD

**Issue by radi2015** [urbica/martin#1248]
(base) [ops@cnhbnp01-0b0d1e ~]$ sudo docker pull ghcr.io/maplibre/martin:mainError response from daemon: manifest for ghcr.io/maplibre/martin:main not found

**Comment by nyurik** [comment]
What type of hardware do you have? OS?

**Comment by radi2015** [comment]
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:20:16 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

**Comment by nyurik** [comment]
@radi2015 I just tried it - works fine. See https://github.com/maplibre/martin/pkgs/container/martin -- all packages are there. Could you test it on another machine?
