### ISSUE TITLE
if it is possible to load postgre function source automatically

### ISSUE THREAD

**Issue by Chengshihao1018** [urbica/martin#1302]
i use PostgreSQL Function Sources in martin.

but i find if i add a new function in postgre after martin service start,martin can`t get this new function,i should restart martin service to load this new function.

i wonder if it is possible to let martin load new function without restarting it?

**Comment by sharkAndshark** [comment]
Hi @Chengshihao1018  Have a good day.
This has been a long time requested feature #288, and @mesudBe-Orbit started working on it #1179

**Comment by Chengshihao1018** [comment]
thx
