### ISSUE TITLE
uploading tiles slows down extremely

### ISSUE THREAD

**Issue by pcace** [urbica/martin#1303]
Hi there, 

i have noticed, that uploading tiles (jsonl) takes longer for each tile. 
i am trying to upload a lot (100.000+ ) tiles to a db using this bash script: 

```bash
for file in "$dir"/*.jsonl; do
    export PGPASSWORD="postgrespw"; cjdb import -H localhost -p 5432 -U postgres -d testcjdb -s cjdb -f "$file" --overwrite # --ignore-repeated-file
done
```

it starts of beeing quite fast ~1s per tile and gets significantly slower for each tile. i have plotted the upload times  for the first houndred tiles (x is tiles, y is time in s):

![image](https://github.com/maplibre/martin/assets/1011875/718545c1-592f-4ac6-8118-fb06c885beb9)

i do have the same issue when uploading the jsonl files by defining not each single jsonl file but rather defining the folder of all jsonl files. 

same result. 

Any Idea how i would find the problem? or is anything known what the issue might be here? 

Thanks a lot!

**Comment by nyurik** [comment]
@pcace Martin does not handle data uploading into databases. You may want to check with the team that developed `cjdb` tool, or ask on stackoverflow.
