### ISSUE TITLE
dynamic TileJSONs

### ISSUE THREAD

**Issue by indus** [urbica/martin#1314]
I'm dealing with scientific datasets and use martin to serv the values as a global grid to the browser.
At the moment I'm (mis-)using the TileJSON to share some basic stats like min,max,avg of the dataset with the client to use it for proper styling (e.g. endpoints of interpolation for fill-color).
As the dataset changes over time I have to re-run the ```comment on function``` SQL everytime the dataset grows and also restart martin. Is there a way to make the TileJSON response more dynamic?

Or maybe there is another way to make generic JSON metadata endpoints available, without running another server?

**Comment by nyurik** [comment]
that's a cool way to mis-use it :)  There is a lot of need to make it dynamic - see #288 - but sadly noone had any time to get it over the finish line. It's a TODO...  Help wanted :)

**Comment by indus** [comment]
> Help wanted :)

I totally understand - but I've never came in contact with rust.

**Comment by nyurik** [comment]
According to Google, it takes just one month to become mega-productive in Rust ;)

https://www.youtube.com/watch?v=QrrH2lcl9ew

**Comment by CommanderStorm** [comment]
Lets fold this issue into https://github.com/maplibre/martin/issues/288
