### ISSUE TITLE
Error when deploy by AWS Lamda: Unable to load config file .yaml: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by manhcuongincusar1** [urbica/martin#1335]
## Unable to load `.yaml` config file: "No such file or directory (os error 2)" when deployed by AWS Lambda

I have been trying to deploy using the Zip file strategy as described in the [Maplibre documentation for running with Lambda](https://maplibre.org/martin/run-with-lambda.html). However, I'm encountering an issue where the Lambda function cannot find the `.yaml` configuration file, although it is present in my deployment package.

Here's how my root folder in Lambda looks, including the `hello.handler.yaml` file:
![Screenshot of Lambda root folder](https://github.com/maplibre/martin/assets/63287450/b0f590f7-397c-4a30-8a6e-5fdfb86eb1d6)

When I try to run the function via the Function URL, it returns an 'internal error'. Here are the logs:
![Screenshot of Lambda logs](https://github.com/maplibre/martin/assets/63287450/e75382b6-e663-4318-a658-afaadf4a0f94)

Additionally, I have attached the log file for more detailed information:
[log-events-viewer-result.csv](https://github.com/maplibre/martin/files/15263938/log-events-viewer-result.csv)

Can someone help me resolve this issue?

**Comment by jleedev** [comment]
This is because I don't test tutorials after I write them:

https://github.com/maplibre/martin/blob/f5b39b0fba7eb926005afaa4da522af88c108b22/docs/src/run-with-lambda.md?plain=1#L63

```
bash-5.2$ cat <<EOF
> exec martin --config ${_HANDLER}.yaml
> EOF
exec martin --config .yaml
```

Replacing `$` with `\$` in the heredoc would fix this.

**Comment by manhcuongincusar1** [comment]
Thank you
