### ISSUE TITLE
Re-scan of MBTiles directory after adding new files

### ISSUE THREAD

**Issue by RoeeDev** [urbica/martin#1362]
When I run martin with a config file with a directory of MBTiles configured it all works great, but when I try to add new files it doesn't re-scan the directory and I need to re-run martin for it to publish them. Is there a way to make martin publish the new MBTiles files as soon as they are added in the directory?

**Comment by nyurik** [comment]
Duplicate of #288, lots of requests for this, some work is being done in #1179
