### ISSUE TITLE
Update Feature in Database not change in martin

### ISSUE THREAD

**Issue by nyanyaon** [urbica/martin#1393]
i am starting martin and use the tile in the qgis then i have updated feature in database but in the qgis didn't change

**Comment by nyurik** [comment]
You may want to add `--cache-size 0`

**Comment by nyanyaon** [comment]
wow it work thank you, i want to use martin as my geoserver really cool project

**Comment by nyanyaon** [comment]
is martin implement change data capture ?

**Comment by nyurik** [comment]
you mean https://github.com/maplibre/martin/pull/1179 ?

**Comment by nyanyaon** [comment]
Yup that exactly what I mean

**Comment by nyurik** [comment]
yep, it has been on a todo for a long time :)
