### ISSUE TITLE
The authentication type 13 is not supported

### ISSUE THREAD

**Issue by ljh2057** [urbica/martin#1402]
I use the domestic database [highgo Security Edition](https://www.highgo.com/), which is developed based on postgre 12. The user authentication method has been modified. If you use the postgre connection driver directly, the error is as follows: The authentication type 13 is not supported.I have the connection driver corresponding to the highgo database Security Edition. Can I customize the connection driver?Thank you.

**Comment by nyurik** [comment]
Martin uses [postgres crate](https://crates.io/crates/postgres) to connect to PG. I am not sure what you mean by an alternative "driver" in this context - I don't know if Rust supports alternative connectivity methods.

**Comment by CommanderStorm** [comment]
> The user authentication method has been modified

Sorry, but we cannot truely support custom extensions of one vendor like this.
If it is supported upsteam, we will too.
I would suggest to switch to a standard postgis installation and a more recent one than pg 12.

If you have a reason for wanting postgres 12 with the custom auth method, please ask [here](https://github.com/sfackler/rust-postgres) for support of it and include the relevant details why.
