### ISSUE TITLE
Does Martin support dynamically refreshing PostGIS tables?

### ISSUE THREAD

**Issue by xyzhuo** [urbica/martin#1467]
Please, I use Martin to link to PostGIS, and then use qgis data manager to import a new shafile into PostGIS as a new source, but I can't see the new source in Martin. Does Martin support dynamically refreshing PostGIS tables?

**Comment by nyurik** [comment]
It has been a long-requested feature - duplicate of #288

**Comment by xyzhuo** [comment]
Thanks.
