### ISSUE TITLE
db error: unknown GeoJSON type of use function by query_params

### ISSUE THREAD

**Issue by ljh2057** [urbica/martin#1480]
this is my function :
`CREATE OR REPLACE
    FUNCTION f_query_4490(z integer, x integer, y integer,geojson json)
    RETURNS bytea AS $$
DECLARE
  mvt bytea;m FLOAT;minx FLOAT;maxy FLOAT;maxx FLOAT;miny FLOAT;
BEGIN
	m:=POWER(2,z);   
	minx:=x/m*360.0-180;
	maxy:=90-y/m*360;
	maxx:=(x+1)/m*360.0-180;
	miny:=90-(y+1.0)/m*360.0; 
  SELECT INTO mvt ST_AsMVT(tile, 'query_4490', 4096, 'geom') FROM (
    SELECT
      ST_AsMVTGeom(
	      ST_CurveToLine(geometry),
          ST_MakeEnvelope(minx,miny,maxx,maxy,4490),
          4096, 64, true) AS geom
	FROM s_spa 
    WHERE ST_Intersects(geometry, ST_GeomFromGeoJSON(geojson)) and geometry && ST_MakeEnvelope(minx,miny,maxx,maxy,4490)
  ) as tile WHERE geom IS NOT NULL;
  RETURN mvt;
END
$$ LANGUAGE plpgsql IMMUTABLE STRICT PARALLEL SAFE;`
This is the url I use to access this service：
`http://localhost:3000/f_query_4490/5/25/5?geojson={"type":"MultiLineString","crs":{"type":"name","properties":{"name":"EPSG:4490"}},"coordinates":[[[121.81419419,30.99757483],[121.81415067,30.997072052],[121.814124793,30.996835044],[121.814102352,30.996705792],[121.814075445,30.996453818],[121.81407523,30.996446063],[121.814073767,30.996393464],[121.814073064,30.996368209],[121.814074557,30.996295163]]]}`
However I get the following error：
`Unable to get tile 5/25/5 with Json({"geojson": String("{\"type\":\"MultiLineString\",\"crs\":{\"type\":\"name\",\"properties
\":{\"name\":\"EPSG:4490\"}},\"coordinates\":[[[121.81419419,30.99757483],[121.81415067,30.997072052],[121.814124793,30.996835044],[121.814102352,30.996705792],[121.814075445,30.996453818],[121.81407523,30.996446063],[121.814073767,30.996393464],[121.814073064,30.996368209],[121.814074557,30.996295163]]]")}) params from f_rv_query_4490: db error:  unknown GeoJSON type`

**Comment by ljh2057** [comment]
```sql
CREATE OR REPLACE
    FUNCTION f_query_4490(z integer, x integer, y integer,geojson json)
    RETURNS bytea AS $$
DECLARE
  mvt bytea;m FLOAT;minx FLOAT;maxy FLOAT;maxx FLOAT;miny FLOAT;
BEGIN
	m:=POWER(2,z);   
	minx:=x/m*360.0-180;
	maxy:=90-y/m*360;
	maxx:=(x+1)/m*360.0-180;
	miny:=90-(y+1.0)/m*360.0; 
  SELECT INTO mvt ST_AsMVT(tile, 'query_4490', 4096, 'geom') FROM (
    SELECT
      ST_AsMVTGeom(
	      ST_CurveToLine(geometry),
          ST_MakeEnvelope(minx,miny,maxx,maxy,4490),
          4096, 64, true) AS geom
	FROM s_spa 
    WHERE ST_Intersects(geometry, ST_GeomFromGeoJSON(geojson)) and geometry && ST_MakeEnvelope(minx,miny,maxx,maxy,4490)
  ) as tile WHERE geom IS NOT NULL;
  RETURN mvt;
END
$$ LANGUAGE plpgsql IMMUTABLE STRICT PARALLEL SAFE;

**Comment by ljh2057** [comment]
```json
{"type":"MultiLineString","crs":{"type":"name","properties":{"name":"EPSG:4490"}},"coordinates":[[[121.81419419,30.99757483],[121.81415067,30.997072052],[121.814124793,30.996835044],[121.814102352,30.996705792],[121.814075445,30.996453818],[121.81407523,30.996446063],[121.814073767,30.996393464],[121.814073064,30.996368209],[121.814074557,30.996295163]]]}

**Comment by johanjk** [comment]
It's not immediately obvious from the [docs](https://maplibre.org/martin/sources-pg-functions.html), but a function source *must* take only the following arguments: `(z integer, x integer, y integer, query_params json)` 

In your case that means that your `geojson` param in `http://localhost:3000/f_query_4490/5/25/5?geojson=[...]` ends up packed inside `query_params`. and must be accessed as a json key (`"query_params"->>'geojson'`).

Rewrite your query along the lines of:
```sql
CREATE OR REPLACE
    FUNCTION f_query_4490(z integer, x integer, y integer,query_params json)
    RETURNS bytea AS $$
DECLARE
  mvt bytea;m FLOAT;minx FLOAT;maxy FLOAT;maxx FLOAT;miny FLOAT;
BEGIN
	m:=POWER(2,z);   
	minx:=x/m*360.0-180;
	maxy:=90-y/m*360;
	maxx:=(x+1)/m*360.0-180;
	miny:=90-(y+1.0)/m*360.0; 
  SELECT INTO mvt ST_AsMVT(tile, 'query_4490', 4096, 'geom') FROM (
    SELECT
      ST_AsMVTGeom(
	      ST_CurveToLine(geometry),
          ST_MakeEnvelope(minx,miny,maxx,maxy,4490),
          4096, 64, true) AS geom
	FROM s_spa 
    WHERE ST_Intersects(geometry, ST_GeomFromGeoJSON("query_params"->>'geojson')) and geometry && ST_MakeEnvelope(minx,miny,maxx,maxy,4490)
  ) as tile WHERE geom IS NOT NULL;
  RETURN mvt;
END
$$ LANGUAGE plpgsql IMMUTABLE STRICT PARALLEL SAFE;
```

**Comment by ljh2057** [comment]
> It's not immediately obvious from the [docs](https://maplibre.org/martin/sources-pg-functions.html), but a function source _must_ take only the following arguments: `(z integer, x integer, y integer, query_params json)`
> 
> In your case that means that your `geojson` param in `http://localhost:3000/f_query_4490/5/25/5?geojson=[...]` ends up packed inside `query_params`. and must be accessed as a json key (`"query_params"->>'geojson'`).
> 
> Rewrite your query along the lines of:
> 
> ```sql
> CREATE OR REPLACE
>     FUNCTION f_query_4490(z integer, x integer, y integer,query_params json)
>     RETURNS bytea AS $$
> DECLARE
>   mvt bytea;m FLOAT;minx FLOAT;maxy FLOAT;maxx FLOAT;miny FLOAT;
> BEGIN
> 	m:=POWER(2,z);   
> 	minx:=x/m*360.0-180;
> 	maxy:=90-y/m*360;
> 	maxx:=(x+1)/m*360.0-180;
> 	miny:=90-(y+1.0)/m*360.0; 
>   SELECT INTO mvt ST_AsMVT(tile, 'query_4490', 4096, 'geom') FROM (
>     SELECT
>       ST_AsMVTGeom(
> 	      ST_CurveToLine(geometry),
>           ST_MakeEnvelope(minx,miny,maxx,maxy,4490),
>           4096, 64, true) AS geom
> 	FROM s_spa 
>     WHERE ST_Intersects(geometry, ST_GeomFromGeoJSON("query_params"->>'geojson')) and geometry && ST_MakeEnvelope(minx,miny,maxx,maxy,4490)
>   ) as tile WHERE geom IS NOT NULL;
>   RETURN mvt;
> END
> $$ LANGUAGE plpgsql IMMUTABLE STRICT PARALLEL SAFE;
> ```

Suddenly it dawned on me. I tested it according to your method and now I can access it successfully. Thank you very much!

**Comment by ljh2057** [comment]
Problem solved, thanks
