### ISSUE TITLE
How to avoid WHERE geom IS NOT NULL clause in pg function?

### ISSUE THREAD

**Issue by Zia-** [urbica/martin#1481]
Why do we have **WHERE geom IS NOT NULL** clause in the following pg function which I copied from [here](https://maplibre.org/martin/sources-pg-functions.html)?

```
CREATE OR REPLACE
    FUNCTION function_zxy_query(z integer, x integer, y integer)
    RETURNS bytea AS $$
DECLARE
  mvt bytea;
BEGIN
  SELECT INTO mvt ST_AsMVT(tile, 'function_zxy_query', 4096, 'geom') FROM (
    SELECT
      ST_AsMVTGeom(
          ST_Transform(ST_CurveToLine(geom), 3857),
          ST_TileEnvelope(z, x, y),
          4096, 64, true) AS geom
    FROM table_source
    WHERE geom && ST_Transform(ST_TileEnvelope(z, x, y), 4326)
  ) as tile WHERE geom IS NOT NULL;

  RETURN mvt;
END
$$ LANGUAGE plpgsql IMMUTABLE STRICT PARALLEL SAFE;
```

Although no row in my postgis table has a NULL geom cell, I'm getting a lot of NULL values (most likely the reason why whoever wrote the above function added this where clause). 

My Question is why/how can I have a NULL geom coming out of ST_AsMVTGeom()? What should I do on my db end to avoid geoms getting NULL during ST_AsMVTGeom() step?

**Comment by nyurik** [comment]
my guess is that you have polygons or polylines (but not points) - so when `ST_AsMVTGeom` converts it to a given tile, the geometry might become so small that it disappears for a given zoom level - thus `NULL`.  In theory, `ST_AsMVT` should remove any such rows from the result - or else it simply wouldn't be a valid MVT (each MVT feature must have some geometry)

**Comment by Zia-** [comment]
That makes total sense to me; and yes, there are a lot of very small polygons and polylines. Also, I didn't notice this behavior when tested against point features. 
So, it all lines up; although will do further tests. Closing the issue for now. Thanks a lot.
