### ISSUE TITLE
how to visit web-ui

### ISSUE THREAD

**Issue by ljh2057** [urbica/martin#1483]
web_ui: enable-for-all

**Comment by CommanderStorm** [comment]
Hi @ljh2057
The webui is not currently released. It is currently just plumbing to build one.
If you want to contribute on this, please see #1120
See https://github.com/maplibre/martin/pull/1395 for additional on the plumbing

**Comment by ljh2057** [comment]
> 你好@ljh2057 目前WebUI尚未发布。目前只是构建WebUI的管道。 如果您想做出贡献，请参阅#1120有关管道的更多信息， 请参阅#1395

ok,thanks.
