### ISSUE TITLE
Need to Restart Martin Service to Reflect Updated Data in PostGIS Tables

### ISSUE THREAD

**Issue by leoneljdias** [urbica/martin#1561]
After making updates to data in PostGIS tables, these changes aren’t reflected in the tiles served by Martin until the service is restarted. This makes it challenging to display real-time or frequently updated data without manual intervention.

**Comment by nyurik** [comment]
Agree - we need someone to work on this, see #288

**Comment by leoneljdias** [comment]
Thanks!

**Comment by Krizz** [comment]
You can create a function source that takes the table name as a parameter to dynamically generate tiles.
https://gist.github.com/Krizz/7a1046b7a04d45e1d682502dfc8d94b7
