### ISSUE TITLE
Send table_name via query_params

### ISSUE THREAD

**Issue by azhe403** [urbica/martin#243]
Is possible send `table_name` via `query_params`?

```
curl \
  --data-urlencode 'table_name=public.table_name' \
  --data-urlencode 'objectParam={"answer" : 42}' \
  --get localhost:3000/rpc/public.function_source/0/0/0.pbf
```

**Comment by stepankuzmin** [comment]
Hi @azhe403 

Yes, that should be possible. In your case, `table_name` will be accessible as `query_params->'table_name'` in your `public.function_source` function. However, it may introduce security vulnerability, so be careful
