### ISSUE TITLE
Website Unavailable?

### ISSUE THREAD

**Issue by douglasg14b** [urbica/martin#302]
When I try and go to https://martin.urbica.co/ I get an SSL error, and if I push through that am shown:

![image](https://user-images.githubusercontent.com/1400380/150654679-0490941e-43ca-4ded-9bd0-4d449027519b.png)

![image](https://user-images.githubusercontent.com/1400380/150654702-b4ea2b82-8e97-437a-95f3-698eef5711b4.png)

**Comment by stepankuzmin** [comment]
Hi @douglasg14b,

Yes, it's under maintenance currently. Sorry for the inconvenience

**Comment by stepankuzmin** [comment]
Hi @douglasg14b

The website is available again https://martin.urbica.co/
