### ISSUE TITLE
Maintenance status?

### ISSUE THREAD

**Issue by edtjones** [urbica/martin#304]
Hi folks,

I'm just wondering if Martin is actively in use and maintained by Urbica? I can see a few PRs from late last year, and the website has been out of action for a couple of weeks. I'm just assessing options for dynamic MVT tiling and want to make sure I don't introduce an unsupported dependency to our stack :)

Thanks

Ed

**Comment by stepankuzmin** [comment]
Hi @edtjones and all,

I still maintain Martin. However, the development pace is not as active as it used to be. The website is available [here](https://martin.stepankuzmin.com/) at the moment, but soon it will be available at [martin.urbica.co](https://martin.urbica.co/) again.

I really appreciate all the users of this small open source project, and you are the reason I do it. But as far as I do it in my free time, I can't commit to lifetime support.

**Comment by edtjones** [comment]
Thank you for all your work Stepan. 🙂
