### ISSUE TITLE
Add default SRID support

### ISSUE THREAD

**Issue by sharkAndshark** [urbica/martin#306]
Hi all！
 I love and use matin a lot in my daily work!  I like the lightweight of this tile server. Thanks!

And i noticed that martin just ignore view/table  which SRID is 0.But all  pg  view with geomtry column have SRID  0 and can not changed.  
```
SELECT UpdateGeometrySRID('all_roads_with_props', 'geom',4490)
> ERROR:  "all_roads_with_props" is not a table, composite type, or foreign table
```
Is there some reason for this behavior?

**Comment by sharkAndshark** [comment]
Is it reasonably that add a default SRID CLI argument to martin?  
I'd love to take it.

**Comment by stepankuzmin** [comment]
Hi @sharkAndshark 

You can create a configuration file and specify the SRID for each table in it
See https://github.com/urbica/martin#configuration-file

**Comment by sharkAndshark** [comment]
> Hi @sharkAndshark
> 
> You can create a configuration file and specify the SRID for each table in it See https://github.com/urbica/martin#configuration-file

Hi @stepankuzmin . Thanks for your response.  
For pg with a lot of views it's not convenient  writting config file.  It just ignore pg view when running martin from CLI.

**Comment by stepankuzmin** [comment]
Hi @sharkAndshark 

Now you can specify the default SRID using the CLI param:

```sh
martin --default-srid 4326
```

environment variable:

```sh
DEFAULT_SRID=4326 martin
```

…or config option:

```yaml
default_srid: 4326
```
