### ISSUE TITLE
Optimize prettify_error

### ISSUE THREAD

**Issue by nyurik** [urbica/martin#348]
Looking at the code, it seems the `prettify_error` causes some significant slowdowns because it gets called on every request, creating an owned string https://github.com/maplibre/martin/blob/4a26366a606cdb7371828b57105c896552dd66a9/src/utils.rs#L11-L13 I suspect the intention was to call it only on error.  Also, it might be more efficient if there were two functions - one for the static str, and another with a formatter.

**Comment by sharkAndshark** [comment]
@nyurik Could i take this ?

**Comment by nyurik** [comment]
> @nyurik Could i take this ?

@sharkAndshark sure!

**Comment by sharkAndshark** [comment]
Hi @nyurik ,I'm a rust newbee,Is this the proper way?   
FUNCTION UPDATE 
```rust
pub fn prettify_error<E: std::fmt::Display>(message: &str,error:E) -> std::io::Error {
    std::io::Error::new(std::io::ErrorKind::Other, format!("{}: {}", message, error))
}
```
CALLER EXAMPLE 1
```rust
result.map_err( |error| prettify_error("Can't read config file",error))?;
```
CALLER EXAMPLE 2
```rust
result.map_err( |error| prettify_error(format!(
                "Can't get \"{}\" tile at /{}/{}/{}",
                self.id, &xyz.z, &xyz.x, &xyz.z
            ).as_str(),error))?;
```

**Comment by nyurik** [comment]
@sharkAndshark sorry for delayed response - i can't say i'm an expert either, but i'll pretend :)  I was thinking of two functions, IF it is possible to do:

```rust
// for static strings, prettify_error() returns a function that will be called by map_err in case of an error.
result.map_err(prettify_error("static string"))?;

// For formatted string, use a macro that accepts the error, following by standard format! params (I think it recently became possible to do this in Rust)
result.map_err(|error| prettify_error_fmt!(error, "format_string", param1, param2, ...))?;
```
