### ISSUE TITLE
Allow minimize tile size according config file

### ISSUE THREAD

**Issue by sharkAndshark** [urbica/martin#362]
Maybe supply some ways to minimize tile size according config file,like  
* Fields filter.Not bump all fields into vector tile.
* St_Simplify
* Data filter based on area or length
* Something else...

**Comment by stepankuzmin** [comment]
Hi @sharkAndshark 👋 

You can use [Function Sources](https://github.com/maplibre/martin#function-sources) to achieve this.

**Comment by nyurik** [comment]
closing because this can already be done with existing functionality. Feel free to reopen/comment if not so. Thx!
