### ISSUE TITLE
Website not reachable

### ISSUE THREAD

**Issue by razorness** [urbica/martin#374]
Hello, trying to access https://[martin.urbica.co](https://martin.urbica.co/)/ from germany throws `DNS_PROBE_FINISHED_NXDOMAIN`. So, the domain does not exist.

**Comment by nyurik** [comment]
The project was moved to maplibre, and I don't think urbica is still in business. We may want to create a new site. Help needed:)

**Comment by nyurik** [comment]
Thanks @razorness , yes, it's dead, we should create a new one. See #403
