### ISSUE TITLE
Update url in description of repo

### ISSUE THREAD

**Issue by birkskyum** [urbica/martin#383]
I believe the url is broken [martin.urbica.co](https://martin.urbica.co/)

<img width="521" alt="Screenshot 2022-08-12 at 18 15 01" src="https://user-images.githubusercontent.com/74932975/184398811-4fc7134e-706f-4aa0-a4aa-af9cbacfdaf1.png">

**Comment by nyurik** [comment]
Yes,  needs to be fixed.  We should create a documentation site under maplibre.org

**Comment by nyurik** [comment]
i removed the link, eventually we may want to re-add a link to the maplibre doc page.  Urbica used to have an awesome site as documented at #403, would be awesome to recreate it.
