### ISSUE TITLE
Add feature count limit

### ISSUE THREAD

**Issue by Kanahiro** [urbica/martin#384]
- With PostgreSQL, martin can serve tiles in a reasonable latency, when tile-size is relatively small.
- Current martin has no limitation in feature count in one tile.
- When you request a tile including large amount of features, response become somewhat heavy. 

Idealy, it is the best to simplify features and drop tiny ones on-the-fly but this seems not to be practical in terms of performance.
Therefore, I would like to propose to add feature count limit option in config. I mean developer set maximum number of features in one tile, like following

```
max_feature_count: 10000
```

Elasticsearch seems to take this approach in `size` parameter (off course it is not totally same and comparable...).
https://www.elastic.co/guide/en/elasticsearch/reference/master/search-vector-tile-api.html

**Comment by nyurik** [comment]
Thanks for the suggestion, I added it to the #430 discussion as one of the config params.  See if this would fit the need.

**Comment by nyurik** [comment]
First draft of this feature is done in #576

**Comment by nyurik** [comment]
Done in 0.7.1 release
