### ISSUE TITLE
Automate docker image publishing

### ISSUE THREAD

**Issue by nyurik** [urbica/martin#399]
* set up github actions to automatically publish martin under `maplibre/martin`. For now just do it for the main branch as a latest tag.
* set up needed docker-hub secret in maplibre org (@nyurik has the account, need to transfer to the board)
* update the docs in [README](https://github.com/maplibre/martin/blob/main/README.md) 

P.S. A similar workflow is set up in https://github.com/openmaptiles/openmaptiles-tools/blob/master/.github/workflows/push.yml

**Comment by nyurik** [comment]
Update: Docker hub token is now available to Martin repo with read/write access.  Use  `DOCKER_HUB_TOKEN` in github actions to publish to docker

**Comment by wipfli** [comment]
Cool, thanks @nyurik! Can you copy the docker-related secrets to our bitwarden?

**Comment by harsh18262** [comment]
Hi, is help still needed or this issue is resolved?

**Comment by nyurik** [comment]
this is done
