### ISSUE TITLE
Set up Martin documentation site at maplibre.org

### ISSUE THREAD

**Issue by nyurik** [urbica/martin#403]
Urbica used to have an awesome site, viewable at [wayback machine](http://web.archive.org/web/20220512004057/https://martin.urbica.co/).  It would be awesome to have something similar set up under maplibre.org.

@stepankuzmin do you know how it was done, or if that code can be adapted somehow?

**Comment by stepankuzmin** [comment]
Sure! The sources are still available here https://github.com/urbica/martin-landing
The only thing we need is a server where we can run this landing page.

**Comment by birkskyum** [comment]
It would seem like the data set used has been moved.

The site uses:
https://s3.amazonaws.com/nyc-tlc/misc/taxi_zones.zip (A Shapefile)
https://s3.amazonaws.com/nyc-tlc/trip+data/yellow_tripdata_2017-[MONTH 1 - 12].csv

The data is to be found here:
https://www1.nyc.gov/site/tlc/about/tlc-trip-record-data.page

But the data format is now Parquet instead of CSV, due to a 7x reduction in size
https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2017-[MONTH 1 - 12].parquet

**Comment by birkskyum** [comment]
This is the data loading as is:

```sh
for i in 01 02 03 04 05 06 07 08 09 10 11 12
do
    fileName=yellow_tripdata_2017-${i}.csv
    filePath=${HOME}/${fileName}
    wget -O ${filePath} "https://s3.amazonaws.com/nyc-tlc/trip+data/${fileName}"
    dos2unix ${filePath}
    sed -i -e '2d' ${filePath}
    psql -U postgres -d db -c "COPY trips FROM '${filePath}' WITH csv header;"
done
```

**Comment by stepankuzmin** [comment]
I think we can migrate [urbica/martin-landing](https://github.com/urbica/martin-landing) to the MapLibre org (or put it inside the Martin repo) and update it here.

**Comment by birkskyum** [comment]
@stepankuzmin , great! It does look really good - I'm currently trying to run the site with a dataset converted from parquet to CSV, even though parquet definitely would be preferred. I'd be happy to help onboard it and make it run.

**Comment by birkskyum** [comment]
I got the data converted, published, and loaded, and the front end updated to new libraries.

The only thing left appears to be starting the prebuilt front end. When I run `docker-compose up` i see this:

`frontend_1  | /docker-entrypoint.sh: Configuration complete; ready for start up`

Any idea how to take that last step and initiate the start up?

Margin and the db are ready:
`db_1        | 2022-09-16 11:05:11.323 UTC [1] LOG:  database system is ready to accept connections`
`tiles_1     | [2022-09-16T11:05:12Z INFO  martin] Martin has been started on 0.0.0.0:3000.`

The readme says to go to localhost:3000, but there is nothing there.

**Comment by stepankuzmin** [comment]
@birkskyum the front end should be built during the `docker-compose up`. So you should expose the Nginx in the `frontend` service on some port (e.g., `80:80`), and then it should be available on your local machine.


```diff
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
+   ports:
+     - "80:80"
    restart: unless-stopped
    depends_on:
      - tiles
```

**Comment by birkskyum** [comment]
That sure did it, thanks! Thought I tried it already.

I also had to change nginx.conf from https:// to http:// to run locally, but here it is in all it's glory :) 

<img width="559" alt="Screen Shot 2022-09-16 at 14 04 06" src="https://user-images.githubusercontent.com/74932975/190634913-f7987524-f8f1-4dc8-ae4c-0785c7e7573d.png">

**Comment by birkskyum** [comment]
@stepankuzmin I think it's easiest to have this repo on its own, so it's easier to check it out for deployment, etc.

**Comment by birkskyum** [comment]
https://martin.maplibre.org
