### ISSUE TITLE
why Rust language is used?

### ISSUE THREAD

**Issue by sudoStatus200** [urbica/martin#411]
As I see actual  computation and transformation is done in postgis only, so why rust?

**Comment by nyurik** [comment]
There are several reasons:
* stability: any server-side code requires far higher crash resilience then a client. Tileserve-gl is consistently crashing in production after some time (personal experience). Rust is built from the ground up to ensure stability and far fewer errors than any system I know ("if it compiles, it runs" moto - which means Rust catches a lot more bugs during compilation than other languages)
* Per [referenced study](https://aws.amazon.com/blogs/opensource/sustainability-with-rust/#temp:C:YMB37456d154ebfc92c7c2114a81)
   * energy efficiency:  Rust is 4.5x times more energy efficient than javascript
   * performance: Rust is 6.5x times faster than javascript

**Comment by maxammann** [comment]
I also guess the original author had reasons :)

**Comment by maxammann** [comment]
Feel free to reopen, if you have further questions.
