### ISSUE TITLE
Test Docker image in CI

### ISSUE THREAD

**Issue by gbip** [urbica/martin#436]
The goal of this issue is to catch issues such as #423 before they reach production users.

The biggest issue with this is that the tests are not build as part of the docker image.

**Comment by gbip** [comment]
I'm not sure about how to run the tests in the docker image.

Since we only have the final martin binary in the image, running the tests does not seems trivial.

**Comment by nyurik** [comment]
There are two ways:
* start martin docker that uses pg docker (e.g. using bridged network or shared port), and then run all curl commands from the host against the martin that runs in a docker
* create a shell script that runs in the martin docker image. The script would do these steps (see [this script](https://github.com/openmaptiles/openmaptiles-tools/blob/6ece174d924e6a461cbe6c0139c4159a96397ac0/tests/test-tools.sh#L64) for a similar process)
  * start martin binary in a background, e.g. with `martin &`
  * on exit trap, kill martin process (see link)
  * install curl
  * run all curl commands against the localhost:3000

**Comment by gbip** [comment]
Ok, I thought you wanted to run the test suite form within the container.

**Comment by nyurik** [comment]
@gbip that's the second option I gave, but either way would work

**Comment by gbip** [comment]
I think I'm talking about the rust unit tests, while you are talking about some kind of integration tests that I am not aware of :)

I'll take a look at it next week (if my schedule allows it).

**Comment by nyurik** [comment]
Ah, yes, the tests we need are integration tests. See https://github.com/maplibre/martin/blob/55e0b9a810528739116f87bf2c2d0fa045b3cfc1/.github/workflows/ci.yml#L133-L138

P.S. ideally these should be moved to some shell script

**Comment by gbip** [comment]
I'm looking at this right now.

**Comment by nyurik** [comment]
A lot of this work was done in #467 , but more is needed. Next step is to run some scripts as part of the docker build...
