### ISSUE TITLE
macOS binary is failing to start

### ISSUE THREAD

**Issue by stepankuzmin** [urbica/martin#460]
The macOS build from the latest RC build is failing to start https://github.com/maplibre/martin/releases/tag/v0.6.0-rc.3

```shell
dyld[88901]: Library not loaded: '/usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib'
  Referenced from: '/opt/homebrew/Cellar/martin/0.6.0-rc.3/bin/martin'
  Reason: tried: '/usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib' (no such file), '/usr/local/lib/libssl.1.1.dylib' (no such file), '/usr/lib/libssl.1.1.dylib' (no such file)
```

**Comment by nyurik** [comment]
Why didn't our CI catch this? Do we need to implement #433 for this?

**Comment by nyurik** [comment]
@stepankuzmin can this be closed?

**Comment by stepankuzmin** [comment]
Yep, [martin-Darwin-aarch64.tar.gz](https://github.com/maplibre/martin/releases/download/v0.6.1/martin-Darwin-aarch64.tar.gz) from [v0.6.1](https://github.com/maplibre/martin/releases/tag/v0.6.1) works for me 👍
