### ISSUE TITLE
Update to tilejson 3.0

### ISSUE THREAD

**Issue by kylebarron** [urbica/martin#465]
In the latest version of `martin`, the tilejson endpoints support tilejson 2.2.0:
https://github.com/maplibre/martin/blob/01b9fe4fe1d97f15f6dea0d0344da6d705c249b2/tests/function_source_test.rs#L44

The [latest version of the TileJSON spec](https://github.com/mapbox/tilejson-spec/tree/master/3.0.0) is now 3.0, which adds extra helpful information, such as the [schema of the properties in the tiles](https://github.com/mapbox/tilejson-spec/tree/master/3.0.0#33-vector_layers). This makes it easier for some systems to consume. Would martin be interested in updating to this?

**Comment by nyurik** [comment]
I'm all for it, please submit a PR. I have implemented tilejson v3 support in https://github.com/georust/tilejson , so it should be fairly trivial to migrate.

**Comment by nyurik** [comment]
this was done in #549
