### ISSUE TITLE
Set protocol to https for tiles if JSON source is requested by https

### ISSUE THREAD

**Issue by korywka** [urbica/martin#480]
If martin is run by `http`, it creates source URL with `http` protocol for `tiles` key, like:
`http://maps.example.com/tiles/public.zip_codes/{z}/{x}/{y}.pbf`

But it we serve our site and martin by `https` with nginx, `http` content (tiles) can't be loaded with `https`.

Current solution is to hardcode all the JSON object for style (type, tiles, minzoom, maxzoom, ...) at the client side with `https` for tiles URL.

Am I missing something and is it possible to set tiles protocol? If not, I think it would be nice to make it configurable.

Another cool solution I think is to set `https` if `https://maps.example.com/tiles/public.counties.json` is requested by `https`. It will not need any additional options.

Protocol mismatch is on the screenshot (source is requested by `https`):

<img width="1004" alt="image" src="https://user-images.githubusercontent.com/988471/201765659-065cc440-d249-4b9d-a3cd-720643691eaf.png">

**Comment by korywka** [comment]
Heh, martin will never know about HTTPS cause it is behind nginx. Looks like it can be fixed with option only.

**Comment by stepankuzmin** [comment]
Hey @korywka 👋 

You can try Rewriting URL with https://github.com/maplibre/martin#rewriting-urls

**Comment by korywka** [comment]
@stepankuzmin yep, this fixed it:
<img width="494" alt="image" src="https://user-images.githubusercontent.com/988471/201769294-5becfa1b-fdcd-41f9-8512-b8d776f90a17.png">

Thanks! ❤️
