### ISSUE TITLE
Add `Linux/arm64/v8` docker image

### ISSUE THREAD

**Issue by ArtOshchepkov** [urbica/martin#505]
Thanks for excellent Software!
For now, there is only `linux/amd64` build in the [docker hub](https://hub.docker.com/r/maplibre/martin/tags?page=1&ordering=-name).
So deploying Martin to AVR production server is not possible via docker (but very desirable!)

**Comment by nyurik** [comment]
@ArtOshchepkov thx, it does make sense. I have no access to AVR hardware, so no way to test. Could you make changes to [.github/workflows/docker.yml](https://github.com/maplibre/martin/blob/main/.github/workflows/docker.yml) and/or to the [Dockerfile](https://github.com/maplibre/martin/blob/main/Dockerfile) and submit a PR?  Thx!

**Comment by nyurik** [comment]
@ArtOshchepkov which target would this be in [this list](https://doc.rust-lang.org/beta/rustc/platform-support.html)?

**Comment by ArtOshchepkov** [comment]
We decided to switch to a classic x86 server, so now I don't have access to AVR hardware as well :)
But it solved the problem.
So if anonyms uses martin for a new project, switching to x86 is an option

**Comment by nyurik** [comment]
@ArtOshchepkov sure, but I think it might be useful to others - do you know the more specific details of the hardware you had or others might have? Is it listed [here](https://doc.rust-lang.org/beta/rustc/platform-support.html) ?

**Comment by maxammann** [comment]
Similar issues exist for other docker images like postgis: https://github.com/postgis/docker-postgis/issues/216

I can see that margin already support aarch64/arm64 so the only thing we need to do is to publish a arm64 docker image. How are docker images currently uploaded?
