### ISSUE TITLE
Improve MapLibre demo to show all available lines/points/polygons from all sources

### ISSUE THREAD

**Issue by nyurik** [urbica/martin#536]
Current martin [demo](https://github.com/maplibre/martin/blob/main/tests/debug.html) page shows a list of all available sources (by first calling the `/catalog` API), and allows the users to turn on/off each source individually.  There are some limitations that need to be addressed:

* it relies on the tilejson to tell it which type of information is in the data. Instead, it should allow all types (points / lines / ...), and visualize them all
* it shows everything in the same color - each layer should get its own color, e.g. randomly when the layer is enabled, and possibly with a color picker for extra bonus.
* it requires to know the name of each layer in the MVT. Instead, it should use the "inspection" mode, where all layers are shown regardless of their name
   * it could use multiple colors if the MVT has more than one layer
* make the left sidebar resizable
* make the list of the sources substring-filterable with an input box at the top
* ...?

### Requirements
* keep it to a single javascript file
* keep it as simple as possible

### Instructions for those who may want to help with this
* install rust
* install docker and docker-compose
* run `rust install just`
* run `just run`
* open `tests/debug.html` file in your browser by copy/pasting the full path to it

**Comment by Binabh** [comment]
@nyurik I would like to work on this. I am confused in two things.
1. How can we determine the geometry type in order to provide appropriate type in layer?
2. What is inspection mode?

**Comment by nyurik** [comment]
The "inspector" mode is the answer to the first question too - something similar to [mapbox-gl-inspect](https://github.com/lukasmartinelli/mapbox-gl-inspect) but for MapLibre (the same thing should exist in Maputnik I would think, or at least it should be ported if not). This way you don't really care what type of geometry each layer has - you just draw them all.

**Comment by Binabh** [comment]
Thank you @nyurik I shall look into mapbox-gl-inspect. Also I have opened a draft PR for other features. Please provide your feedback if any.

**Comment by tordans** [comment]
Thanks for [working on this](https://github.com/maplibre/martin/pull/660)! Is there a Martin instance that we can use to link from the Readme to preview the feature?

**Comment by nyurik** [comment]
Seems this was closed by accident - debug.html still doesn't show polygons, and we need to figure out the "x-ray" mode so that it shows all content without knowing what that content is beforehand

**Comment by lodi-g** [comment]
Hi,

I'm researching a bit this issue. From my understanding what is missing is the following the source introspection to select the right layer (right now the source and the source-layer have to have the same name).

Some suggestions though:
* It would be useful to have a popup with attributes upon clicking on a point
* It would be useful to be able to open this page with the "base" martin (without `cargo`/`just`), e.g. `martin debug-page ...`
* It would be useful to group sources that does not come from the user itself, see screenshot where my source is "Macedonia" and the rest is something I have no idea about 
<img width="324" alt="image" src="https://github.com/maplibre/martin/assets/4528943/7cfde04d-93d5-4766-b444-c53a4fe7a5ad">

What do you think?

**Comment by tordans** [comment]
FYI this might be something that can be reused or be used as an inspiration https://twitter.com/j_igarashi/status/1663405008359129088

**Comment by sharkAndshark** [comment]
For display all layers in Martin withou knowing the geometry type before, Could this benefit from [Future-proof source catalog](https://github.com/maplibre/martin/pull/754) .Like add the geometry type in metadata?    
What's the correct way to implement this?
*  [Add a custom layer](https://maplibre.org/maplibre-gl-js/docs/examples/custom-style-layer/)
* Add geometry type in metadata
* Other ways?

**Comment by nyurik** [comment]
My understanding is that maplibre inspection mode should allow showing all data without having any Metadata.  Same as what Maputnik does

**Comment by sharkAndshark** [comment]
Hi @nyurik Have a lovely day. :D
Some thoughts on this. The idea is displaing each layer in source as  circle, linestring and polygon with filter like `['==', '$type', 'LineString']`   at same time  
 

```js
foreach(var source in sources){
// add circle layer 
        map.addLayer({
          id: source.id + "_circle",
          ...
          filter: ['==', '$type', 'Point'],
          paint: {
            "circle-color": stringToColour(source.id),
            "circle-radius": 2
          }
        });

// add linestring layer
        map.addLayer({
          id: source.id + "_line",
          type: "line",
          ....
          filter: ['==', '$type', 'LineString'],
          paint: {
            'line-color': stringToColour(source.id),
          }
        });
// add polygon layer
...
}
```
![image](https://github.com/maplibre/martin/assets/42399654/a43bd757-0a26-40f6-9ce1-c452429d2acc)
