### ISSUE TITLE
Why don't you take the front part？？   

### ISSUE THREAD

**Issue by BigData-YC** [urbica/martin#538]
the version 0.6.1
Configured table source "aaaa" from "public.aaaa" with "geom" column (GEOMETRY, SRID=3857)
Configured table source "aaaa.1" from "test.aaaa" with "geom" column (GEOMETRY, SRID=3857)

Who knows what  aaaa.1  is？？？？
This is very difficult to understand！！！！！

**Comment by nyurik** [comment]
If you have a table `aaaa` in a schema `public` with two geometry columns, Martin will create two sources named `aaaa` and `aaaa.1`.

I am thinking of making the naming for auto discovery more configurable soon

**Comment by nyurik** [comment]
Update: i just noticed that you have two tables with the same name but in two different schemas.

Please take a look at the https://github.com/maplibre/martin/issues/512 -- for how we can make this configurable

**Comment by nyurik** [comment]
added in #546
