### ISSUE TITLE
No response from server

### ISSUE THREAD

**Issue by miketahani** [urbica/martin#542]
I am unable to get a response besides 404 on http or an SSL error on https when attempting to GET from the server. M1 MBP, tried `curl`, latest FF, latest Brave.

To reproduce:

1. Install Postgres via Postgres.app (https://postgresapp.com/)
2. Set up PostGIS in DB, add data
3. Install martin via `brew install martin` (after tapping)
4. Run `martin postgresql://postgres@localhost/my_db`
5. `curl localhost:3000` - nothing returned
6. `curl https://localhost:3000` - `curl: (35) error:1404B42E:SSL routines:ST_CONNECT:tlsv1 alert protocol version`
7. Visit `localhost:3000` in browser (both FF and Brave in Private Mode, all extensions disabled) - 404
8. Same as 7, but `https://localhost:3000`:

```
FF: 
Secure Connection Failed

An error occurred during a connection to localhost:3000. SSL received a record that exceeded the maximum permissible length.

Error code: SSL_ERROR_RX_RECORD_TOO_LONG

The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
Please contact the website owners to inform them of this problem.

Brave: 
This site can’t provide a secure connection
localhost sent an invalid response.
ERR_SSL_PROTOCOL_ERROR
```

Output from server for curls when running with debug log:

```
http:
[2022-12-26T21:47:31Z DEBUG tokio_reactor] adding I/O source: 4194304
[2022-12-26T21:47:31Z DEBUG tokio_reactor::registration] scheduling Read for: 0
[2022-12-26T21:47:31Z DEBUG tokio_reactor::registration] scheduling Read for: 0
[2022-12-26T21:47:31Z INFO  actix_web::middleware::logger] 127.0.0.1:53355 "GET / HTTP/1.1" 404 0 "-" "curl/7.84.0" 0.000055
[2022-12-26T21:47:31Z DEBUG tokio_reactor] dropping I/O source: 0

https:
[2022-12-26T21:47:36Z DEBUG tokio_reactor] adding I/O source: 4194304
[2022-12-26T21:47:36Z DEBUG tokio_reactor::registration] scheduling Read for: 0
[2022-12-26T21:47:36Z DEBUG tokio_reactor::registration] scheduling Read for: 0
[2022-12-26T21:47:36Z DEBUG tokio_reactor] dropping I/O source: 0

```

Any ideas? Hoping this is some obvious error on my part.

**Comment by nyurik** [comment]
Martin doesn't support https (yet?). What do you get from http?

**Comment by miketahani** [comment]
The server reports a 404 with an empty response - `[2022-12-26T21:47:31Z INFO  actix_web::middleware::logger] 127.0.0.1:53355 "GET / HTTP/1.1" 404 0 "-" "curl/7.84.0" 0.000055`

**Comment by nyurik** [comment]
I think that is normal in that version (I have added something to the root since than). 

Take a look at the api section https://github.com/maplibre/martin/tree/v0.6#api

**Comment by miketahani** [comment]
Ah, thank you so much! I was using the information in the README in the main branch and completely missed the gigantic warning "This documentation is for the unreleased main branch.". Apologies and thanks for the quick response!
