### ISSUE TITLE
Small typo in the docker-compose.yml template inside README

### ISSUE THREAD

**Issue by spelexander** [urbica/martin#544]
First off this is an awesome project, thanks so much for creating it. 

The docker-compose.yml example in README.md had an incorrect db username for martin:

`DATABASE_URL=postgresql://postgresql:password@db/db` 

Should be changed to: 

`DATABASE_URL=postgresql://postgres:password@db/db`

Would have happily contributed this change myself, thanks!

**Comment by nyurik** [comment]
Thanks @spelexander , I fixed it in #545. Please note that the main readme is for the main branch, not the released v0.6 (see note at the top)...  It seems we may have to move the docs from the readme to sub-readmes, with the main readme just having a list of versions with pointers...
