### ISSUE TITLE
Response compression

### ISSUE THREAD

**Issue by msbarry** [urbica/martin#577]
Currently, when serving raster tiles with an from an mbtiles/pmtiles archive martin tries to compress them, which doesn't help (often hurts) image formats that already have compression baked in.  Also, when requesting vector tiles without an `accept-encoding` header, martin still serves them with `content-encoding: gzip`.

I think it should probably do something like:

mbtiles storage format | accept-encoding | response encoding
-- | -- | --
mvt (gzipped) | "" | decompress it since client doesn't want gzip
webp/png (not gzipped) | "" | don't compress it since client doesn't want compressed
mvt (gzipped) | "gzip/br" | pass-through compressed data from archive
webp/png (not gzipped) | "gzip/br" | don't compress it since compression won't help

**Comment by nyurik** [comment]
Thanks @msbarry!  Do you by any chance have some small pmtiles and/or mbtiles file with such content with a CC0 or similar license?  It could really benefit the automated testing.

**Comment by msbarry** [comment]
Yeah, here's zoom levels 0 and 1 from natural earth shaded relief raster tiles in mbtiles and pmtiles format:

[raster.zip](https://github.com/maplibre/martin/files/10771853/raster.zip)

**Comment by msbarry** [comment]
pngs:

[raster.zip](https://github.com/maplibre/martin/files/10774125/raster.zip)

**Comment by nyurik** [comment]
Thanks @msbarry , I merged and released this as part of 0.7.1

**Comment by msbarry** [comment]
Awesome thanks @nyurik !
