### ISSUE TITLE
Source as table doesn't generate `vector_layers` key

### ISSUE THREAD

**Issue by korywka** [urbica/martin#583]
`vector_layers` [key is a required](https://github.com/mapbox/tilejson-spec/tree/master/3.0.0#33-vector_layers) (do not know why) of tilejson and should contain at least all ids and fields of the source.

For example, it is the easy way to find what to put in `source-layer` field of `map.addLayer` method.

Quick view of what I am talking about:

![image](https://user-images.githubusercontent.com/988471/220438475-edbe18c6-a46e-4f66-9571-2939e0059688.png)

And in tests martin have it too:
https://github.com/maplibre/martin/blob/9e5ed2fc02a7815f1e32b44bcc7a882e763898af/tests/expected/auto/mb_mvt.json#L23-L33

**Comment by nyurik** [comment]
That test is for `.mbtiles` file which has that content as part of the metadata table. We will need to generate something similar for postgres. Thx for reporting.

**Comment by nyurik** [comment]
ok, implemented first pass, need some feedback ^
