### ISSUE TITLE
Allow table sources to override the MVT layer ID

### ISSUE THREAD

**Issue by nyurik** [urbica/martin#597]
The PG table source should be able to set the layer ID name to be different from the source ID.

* For preconfigured tables it may be `layer_id` field
* For autodiscovered tables it could be `layer_id_format` field with the same features as the `id_format` param

**Comment by nyurik** [comment]
This was mostly implemented in #598 .  For now the `id_format` controls both the source id and the layer id

**Comment by nick-romano** [comment]
@nyurik - is it possible to set the layer id for tables found via `auto_publish`?
