### ISSUE TITLE
Docker paid plan

### ISSUE THREAD

**Issue by wipfli** [urbica/martin#601]
We got an email saying that we will need to pay for docker. I think martin is the only maplibre project using docker hub.

Can we switch martin to ghcr.io i.e. github's container thing? That would be free...

**Comment by wipfli** [comment]
https://blog.alexellis.io/docker-is-deleting-open-source-images/

**Comment by stepankuzmin** [comment]
Yeah, we should migrate to GitHub Docker Registry then :(
