### ISSUE TITLE
linux/arm64/v8 docker images do not exist

### ISSUE THREAD

**Issue by sietsevanderbom** [urbica/martin#603]
I have an Macbook M1. When trying to spin up a container:
```
❯ docker run \
        -p 3000:3000 \
        -e DATABASE_URL=postgresql://postgres@localhost/db \
        maplibre/martin
Unable to find image 'maplibre/martin:latest' locally
latest: Pulling from maplibre/martin
docker: no matching manifest for linux/arm64/v8 in the manifest list entries.
```
Could these be compiled & arranged maybe?

**Comment by nyurik** [comment]
I would love to solve this issue, and we have 90% of the plumbing needed for this, but I have no way to either build or test such image myself (`no_mac`). @stepankuzmin tried to add it in the #602 but it didn't work on GitHub CI. If you can get github ci to generate that image using our existing dockerfile (probably won't need any changes?), I'm all for adding it.

**Comment by Volatus** [comment]
@nyurik I can potentially look into this.
