### ISSUE TITLE
getting v0.5.0 when installing on mac.

### ISSUE THREAD

**Issue by tomeronen** [urbica/martin#616]
I am trying to install martin on macOS but keep getting v0.5.0

RUN:
```
brew tap
brew install martin
```

THEN

```
martin -v
```

and got `v0.5.0`

Am i missing something?

**Comment by nyurik** [comment]
I think we should remove any brew mentioning from the readme for now - I don't have any way to publish it there (no macs), and I think @stepankuzmin had some way of doing it, and we should automate brew publishing from CI. No idea on how to get it done though.

**Comment by stepankuzmin** [comment]
We can still distribute Martin via homebrew, but the current [tap](https://docs.brew.sh/Taps) is in [Urbica org](https://github.com/urbica/homebrew-tap) on GitHub. We can try hosting Martin Homebrew formulae in the Martin repo and use the `brew tap URL` instead of migrating the tap from Urbica org. https://github.com/maplibre/martin/issues/618

**Comment by tomeronen** [comment]
@nyurik, i have a mac, and will be happy to help if there is something i can do

**Comment by nyurik** [comment]
@stepankuzmin ok, lets transfer the repo as `maplibre/homebrew-martin` ?

**Comment by stepankuzmin** [comment]
@nyurik, we can try moving [this formula](https://github.com/urbica/homebrew-tap/blob/master/HomebrewFormula/martin.rb) to the `maplibre/martin` repo first and see if that would work with:

```shell
brew tap https://github.com/maplibre/martin
```

If it doesn't, we'd need to create a separate `maplibre/homebrew-martin` repo. @tomeronen, do you want to take a stab at it?

**Comment by tomeronen** [comment]
@stepankuzmin, Yes i will be happy to! thanks :) i did a test on a fork to the repo and it worked ok. I will create a PR later today.

**Comment by nyurik** [comment]
this should be done. Please test on a Mac and close if works ok

**Comment by nyurik** [comment]
fixed, now on maplibre/homebrew-martin
