### ISSUE TITLE
Add ability to reload schema config/cache without a restart

### ISSUE THREAD

**Issue by saosebastiao** [urbica/martin#630]
I would love to be able to reload the schema config without a full restart. The PostgREST project has two cool ways to do this:

https://postgrest.org/en/stable/schema_cache.html#schema-cache-reloading

* listen for a SIGUSR1 signal
* Using Postgres' LISTEN/NOTIFY with a dedicated channel

The second method in particular is interesting because it allows the DB admin to set up custom triggers that would send notifications to the custom channel any time a geospatial table changes.

**Comment by nyurik** [comment]
This is a dup of #288 - could you add your notes there? I really like the `LISTEN/NOTIFY` idea
