### ISSUE TITLE
TLS handshake timeout

### ISSUE THREAD

**Issue by Graxo** [urbica/martin#661]
Hi,

When using the docker-compose file and the latest manifest i get a TLS handshake error
root@openstreetmap:/opt/martin-main# docker-compose up -d martin

```
Pulling martin (ghcr.io/maplibre/martin:latest)...
latest: Pulling from maplibre/martin
f56be85fc22e: Already exists
246d0dfb756d: Retrying in 1 second
738c1b2345b2: Retrying in 1 second
ERROR: error pulling image configuration: download failed after attempts=6: net/http: TLS handshake timeout
```

Anyone else with this issue?
Im trying to host a map of The Netherlands for a school project, we need a build a navigation system.
So im looking for something to host where i can use (sort of) API calls like https://<host>/{z}/{y}{x}.png

**Comment by nyurik** [comment]
I just ran `docker pull ghcr.io/maplibre/martin:latest` on my linux machine (x64) and it works fine. I suspect you might have non-x64 machine?

**Comment by CommanderStorm** [comment]
> on my linux machine (x64) and it works fine. I suspect you might have non-x64 machine?

Closing as no response => not actionable

We now support multi-platform docker images. (idk if we did a year ago)
