### ISSUE TITLE
Create proper mdbook documentation

### ISSUE THREAD

**Issue by nyurik** [urbica/martin#668]
Our readme is getting to be pretty messy and hard to read, so time to create a better user experience "Rust style" - an mdbook.

One option I have seen is [justfile mdbook generator](https://github.com/casey/just/blob/9f03441eef28fd662b33a8f1961e2ee97b60f7ff/bin/generate-book/src/main.rs) - I think it keeps all the data in the readme, and the generator simply converts that giant readme into multi-paged book that can be easy to publish. This may be the easiest route to take?

Alternatively, we could create a bunch of proper `.md` pages that get compiled into a book.

Lastly, the book should probably be published to the `maplibre.org/martin`

**Comment by sharkAndshark** [comment]
Could we generate a book from another markdown and have a simplified readme? For newcomers to Martin, a shorter and simpler readme would be more friendly I guess

**Comment by nyurik** [comment]
Sure - I am totally ok with going the "regular" route - i.e. set up the `/doc` (or is it `/docs` ?) dir with all the needed `.md` files, and use standard tools to compile it into the book, plus maintain a much shorter version of the readme that simply links to the book.  Do you want to set up the first (semi-empty) book for this?

**Comment by sharkAndshark** [comment]
Yeah sure. Before I give it a try, is this OK like:
1. Set up `/doc/en` dir
2. Copy whole `readme.md` to `/doc/en`,rename it like `book.md`. And keep it a single file ,not many
3. Do a generator like [justfile mdbook generator](https://github.com/casey/just/blob/9f03441eef28fd662b33a8f1961e2ee97b60f7ff/bin/generate-book/src/main.rs)

Or should I do something like [maplibre-rs](https://github.com/maplibre/maplibre-rs/tree/main/docs) did?

I would greatly appreciate any guidance. @nyurik

**Comment by nyurik** [comment]
I think we should be consistent between projects - if @maxammann set it up like that in maplibre-rs, i think its better to keep the same approach?

**Comment by sharkAndshark** [comment]
I'm fine with either. So to keep the same with maplibre-rs?

**Comment by nyurik** [comment]
Yeah, i think that would be the better choice, possibly even simplifying it - i.e. using the recommended way in https://rust-lang.github.io/mdBook/guide/creating.html ?  The fewer customizations we have, the better. We can always make it more complicated later :) 

The only important thing we should think about is how we are going to publish it to `maplibre.org/martin` - not certain yet how that works

**Comment by sharkAndshark** [comment]
For now we could generate [the book](https://github.com/maplibre/martin/pull/681). But how could we use github workflow to publish it in [maplibre.org/martin](https://martin.maplibre.org/). I have no clue. @nyurik

**Comment by nyurik** [comment]
@wipfli do you know?

**Comment by nyurik** [comment]
Horray, its alive!!!  https://maplibre.org/martin/ is now auto-published from the main branch of book from this repo.

**Comment by nyurik** [comment]
Closing this as done, thank you @sharkAndshark , awesome job!!!  See #683 for the next steps
