### ISSUE TITLE
Tile not found - pmtiles file, I know the tiles exist

### ISSUE THREAD

**Issue by tobinbradley** [urbica/martin#675]
I've been digging through the code trying to figure out what's going on with this, but I've hit the limits of my Rust skills, which are approximately none. 

I have a [PMTiles file](https://pub-41c5b8a60911473a932c7ac0e2fd3b63.r2.dev/tiles.pmtiles) (~200mb) that I converted from a MBTiles file using [go-pmtiles](https://github.com/protomaps/go-pmtiles). If I look at it with the [pmtiles preview tool](https://protomaps.github.io/PMTiles/?url=https%3A%2F%2Fpub-41c5b8a60911473a932c7ac0e2fd3b63.r2.dev%2Ftiles.pmtiles#map=7.73/35.454/-80.824), works fine. I server it with go-pmtiles, works fine. I consume it with the PMTiles client-side JS library in MapLibre GL, works fine. I try serving it with martin, and with every request I get tile not found, ex:

```
Tile 7/35/50 not found in tiles-pmtiles
```

I tried turning debuggin on, and it doesn't say much more (at least to my stupid eyes):

```
[2023-05-24T21:45:17Z ERROR martin::srv::server] Tile 7/35/50 not found in tiles-pmtiles
[2023-05-24T21:45:17Z DEBUG actix_web::middleware::logger] Error in response: "Tile 7/35/50 not found in tiles-pmtiles"
[2023-05-24T21:45:17Z INFO  actix_web::middleware::logger] 127.0.0.1 "GET /tiles-pmtiles/7/35/50 HTTP/1.1" 500 39 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36" 0.000065
[2023-05-24T21:45:18Z DEBUG actix_web::middleware::logger] Error in response: "Source service-worker.js does not exist"
[2023-05-24T21:45:18Z INFO  actix_web::middleware::logger] 127.0.0.1 "GET /service-worker.js HTTP/1.1" 404 62 "http://localhost:3000/service-worker.js" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36" 0.000314
```

This happens on both Linux and Windows binary releases and on martin built from the latest source on Linux, so it doesn't appear to be a platform/build issue.

My guess is the ZXY isn't getting translated correctly via thePMTiles header info, which means this might be a bug in the pmtiles crate and not in martin itself. But my rust skills don't extend much past the swearing stage, so I could be totally wrong.

**Comment by nyurik** [comment]
@tobinbradley i guess it will be mega-hard for me to debug it without the original data file. Do you think you somehow can make it much much smaller while still having the bug manifest itself?  This way we can add that tiny pmtiles file to the CI, and ensure that it passes all the tests.  BTW, this would be part of the https://crates.io/crates/pmtiles crate.

**Comment by nyurik** [comment]
oh, silly me, you did post the pmtiles file!  I will try to play with it to see if i can reproduce the issue locally!

**Comment by nyurik** [comment]
(but still - see if you can generate a tiny subset of it, ideally with just one tile)

**Comment by nyurik** [comment]
I think i found the culprit - https://github.com/stadiamaps/pmtiles-rs/pull/17, but it would be awesome to create a lot more tiny test fixture files, where each tile is just a few bytes long with some sequential numbers.

**Comment by tobinbradley** [comment]
Thank you so much! I set Cargo.toml to `pmtiles = { version = "0.2.2"...`, built martin and it finds the tiles perfectly!

I really appreciate you tracking this down in the pmtiles dependency. That's going above and beyond. To paraphrase Jon "maddog" Hall, you will never pay for a beer in my presence.  

Tnanks again!

**Comment by nyurik** [comment]
you are very welcome. This should be part of the v0.8.4 release too (should be published in the next few minutes)
