### ISSUE TITLE
Create a maplibre.org/martin doc site

### ISSUE THREAD

**Issue by nyurik** [urbica/martin#683]
This is a documentation tracking ticket
 
  * [x] enable martin's gh-pages branch as the root of https://maplibre.org/martin
  * [x] automate mdbook compilation and publishing
  * [x] Cleanup the style of the mdbook to be nicer.
    * I really liked [this one](https://google.github.io/comprehensive-rust/) -- and it has edit links to the originating docs too.
  * [x] update [MapLibre project](https://maplibre.org/projects/martin/) page to link to the new book
  * [x] update Martin's README to link to the new site, and remove most of its content
  * [x] restructure/rewrite/improve/cleanup/enhance the book to be the best there is :)

**Comment by birkskyum** [comment]
@nyurik , the "update [MapLibre project](https://maplibre.org/projects/martin/) page to link to the new book" is here https://github.com/maplibre/maplibre.github.io/pull/186

**Comment by nyurik** [comment]
The docs are now in a good new state, thanks everyone!  

https://maplibre.org/martin
