### ISSUE TITLE
Document related issues

### ISSUE THREAD

**Issue by GiserDing** [urbica/martin#719]
1. Please add sample code  to the document

2. I cannot find the functions query API usage

3. Add config.yaml configuration usage instructions

**Comment by CommanderStorm** [comment]
> 1. Please add sample code  to the document

You are likely refering to this https://maplibre.org/martin/using.html

> 2. I cannot find the functions query API usage

You are likely refering to this https://maplibre.org/martin/sources-pg-functions.html

> 3. Add config.yaml configuration usage instructions

currently documented here and in the subfolders
https://maplibre.org/martin/config-file.html


=> closing as I think this is now resolved. If we missed something / something is not clear, I would appreciate feedback where we need to improve the docs most ^^
