### ISSUE TITLE
Overture Maps Schema support

### ISSUE THREAD

**Issue by birkskyum** [urbica/martin#785]
Now that Overture Maps Foundation has begun publishing data, in the Parquet format, it's interesting to figure out what it would take for Martin to support that schema, and what makes sense to do here at all in regards to the Martin project and MapLibre renderer.

The [initial dataset](https://overturemaps.org/overture-maps-foundation-releases-first-world-wide-open-map-dataset/) has 4 different layers (Places of Interest, Buildings, Transportation, Administrative Boundaries) - are some i.e. easier to approach than other?

Schema specification & documentation:
https://docs.overturemaps.org/
https://github.com/OvertureMaps/schema

**Comment by nyurik** [comment]
@birkskyum I am not certain Martin is the right tool for that. I think a much better place would be @msbarry's Planetiler, which would convert that dataset into tiles, and have some sort of a tile index to quickly access them (e.g. pmtiles/mbtiles/...)

**Comment by msbarry** [comment]
Yep! I'm looking into it here: https://github.com/onthegomap/planetiler/issues/636
