### ISSUE TITLE
Requirements for running with psql + whole Europe 700GB db size

### ISSUE THREAD

**Issue by macanton** [urbica/martin#804]
Hello
I am trying to start martin connected to Postgres with Europe osm data imported. The DB size is 700 GB.
Looks like martin is stuck in `tokio_postgres::query] executing statement s18 with parameters: []`.
Can martin handle this size of db and if yes how much time does it need to start apprx?

**Comment by macanton** [comment]
Took about 20 mins to start. I would add info message on start: 'performing initial requests', so that it is not so confusing :)

**Comment by nyurik** [comment]
the size of the DB shouldn't matter - instead, I suspect you don't have GIS indexes (it should warn you about it). Also, you may want to disable bound testing:

```
  -b, --disable-bounds
          Disable the automatic generation of bounds for spatial PG tables
```

I do agree that it may make sense to print a few more notification messages, e.g. 

```
INFO: Searching PostgreSQL tables and functions. If this takes too long, verify your table geo columns have a GIS index, or use --disabling-bounds.
```

Even better approach may be to print a warning only if the startup takes too long.

(feel free to improve the above text)

**Comment by nyurik** [comment]
Closing in favor of #810

**Comment by macanton** [comment]
> the size of the DB shouldn't matter - instead, I suspect you don't have GIS indexes (it should warn you about it). Also, you may want to disable bound testing:
> 
> ```
>   -b, --disable-bounds
>           Disable the automatic generation of bounds for spatial PG tables
> ```
> 
> I do agree that it may make sense to print a few more notification messages, e.g.
> 
> ```
> INFO: Searching PostgreSQL tables and functions. If this takes too long, verify your table geo columns have a GIS index, or use --disabling-bounds.
> ```
> 
> Even better approach may be to print a warning only if the startup takes too long.
> 
> (feel free to improve the above text)

Thank you for your answer, but I imported data using osm2pgsql and I assume it should import indexes 🤔
