### ISSUE TITLE
Question about performance of martin

### ISSUE THREAD

**Issue by qianxiaoming** [urbica/martin#825]
I found that Martin still uses PostGIS functions to generate MVT tiles. The service performance should be mainly affected by the amount of data and the software and hardware configuration of the database, right?  So what are the performance advantages of martin?

**Comment by nyurik** [comment]
A somewhat philosophical question, eh? :)

There are a few things:
* Martin tries to be the thinnest possible layer between the client and MBTile, PMTiles, and PostgreSQL DBs.  The first two are local DBs (sqlite & binary file), the second does rely on PG, but even there it optimizes things with cached queries, etc.
* Martin offers additional services like layer merging (e.g. you can quickly combine MBTiles with PG data, all done in parallel, etc)
* Martin offers some extra stuff like sprite generation - relies mostly on CDN for the actual caching (regened on each request at the moment), and eventually - font SDF conversion.
* Lastly, Martin hopefully one day will offer MVT-generation in-process, getting raw data from the various sources.

As far as comparison with other providers - take a look at https://www.youtube.com/@TobinBradley/search?query=martin -- this person has done a number of videos on Martin, evaluating its performance against other services. At first Martin had a few issues, but now it does perform a lot faster than others (at least according to those videos)

**Comment by qianxiaoming** [comment]
Thank you very much for your reply, and I will understand it more carefully. Thank you!

I think generating MVT tiles may not be a big problem. It should not be difficult to use Rust to rewrite the relevant functions of PostGIS. However, when the amount of data is large, it may be a problem to have to read a large number of required records from the database and transmit them to independent services. I think it may have to be combined with vector pyramid-related technologies.
