### ISSUE TITLE
Please support use encoding UTF-8 

### ISSUE THREAD

**Issue by cbc3929** [urbica/martin#826]
Now in catalog if use Chinese simple  can not show normally like this
<img width="234" alt="image" src="https://github.com/maplibre/martin/assets/70315907/c9e41bce-49e1-4e05-9b40-f5baef72b18b">

**Comment by nyurik** [comment]
It's not the catalog, it's the source ID requirement to be only Latin letters, numbers, and `_-.`

If source ID contains any other character, it is replaced with a minus

**Comment by CNFeffery** [comment]
> Now in catalog if use Chinese simple can not show normally like this <img alt="image" width="234" src="https://user-images.githubusercontent.com/70315907/261895603-c9e41bce-49e1-4e05-9b40-f5baef72b18b.png">

我也是遇到类似的问题，搞得我只能暂时用每个字的首字母作为代替😅

**Comment by nyurik** [comment]
I added a warning in #839 to let users know when sources were renamed
