### ISSUE TITLE
Allow to show tile boundary in `debug.html`

### ISSUE THREAD

**Issue by sharkAndshark** [urbica/martin#845]
Something like this
![image](https://github.com/maplibre/martin/assets/42399654/d38fbe39-0c69-4869-b7c1-507a66b7dc46)

**Comment by nyurik** [comment]
I think @upsicleclown had some experience with this?

P.S. and yes, i agree that the debug screen should show tile boundaries

**Comment by sharkAndshark** [comment]
A [method](https://maplibre.org/maplibre-gl-js/docs/API/classes/maplibregl.Map/#showtileboundaries:~:text=map.ts%3A3347-,showTileBoundaries,-%E2%80%A2%20get%20showTileBoundaries) in `maplibre`:
```javascript
map.showTileBoundaries = true;
```
* The map will render an outline around each tile and the tile ID
* The uncompressed file size of the first vector source is drawn in the top left corner of each tile, next to the tile ID
Seems `maputnik` used this either.

**Comment by nyurik** [comment]
Yes, good idea
