### ISSUE TITLE
Support for older postgis

### ISSUE THREAD

**Issue by sharkAndshark** [urbica/martin#863]
Use [ST_MakeEnvelope](https://postgis.net/docs/en/ST_MakeEnvelope.html) instead of [ST_TileEnvelope](https://postgis.net/docs/en/ST_TileEnvelope.html) to support older postgis.  
The cost of this change is to calculate the `minx` `miny` `max` `maxy` of tile bbox in rust.
```rust
type bbox = [f32;4];
pub fn tile_bbox(zxy: zxy) -> bbox {....}
```
If this's not a big cost, maybe we could support more postgis which though have been outdated years ago....?

**Comment by nyurik** [comment]
@sharkAndshark I don't think it makes any sense to support them. See [support matrix](https://trac.osgeo.org/postgis/wiki/UsersWikiPostgreSQLPostGIS#PostGISSupportMatrix) -- 

Version | PostGIS 2.5 EOL | PostGIS 3.0 | PostGIS 3.1 | PostGIS 3.2 | PostGIS 3.3 | PostGIS 3.4
-- | -- | -- | -- | -- | -- | --
Release date | 2018/09/23 | 2019/10/20 | 2020/12/18 | 2021/12/18 | 2022/08/27 | 20XX/XX/XX

2.5 is already EOL (end of life), and it only supports PostgreSQL 11 & 12. The 3.0 is also 4 years old, so I actually think we should remove support for that pretty soon - not worth supporting it.

**Comment by sharkAndshark** [comment]
Suppose I should update my PostGIS  quickly. Agree, forget the old versions and move on.
