### ISSUE TITLE
How to encode all columns as tile properties using config?

### ISSUE THREAD

**Issue by gtitov** [urbica/martin#872]
As a comment in [config example](https://maplibre.org/martin/config-file.html#config-example) says one must explicitly list columns that should be encoded as tile properties.

> \# List of columns, that should be encoded as tile properties (required)

In my case I don't know columns in advance since they are generated dynamically. I could use `martin postgresql://postgres@localhost/db` to encode all columns automatically but I want to apply `buffer` and `clip_geom` configuration options. 

How can I make Martin encode all columns as tile properties while using config?

**Comment by nyurik** [comment]
I am not sure we support our at this point,  but it sounds like a good use case to support, and relatively easy to implement. Want to try implementing it?

**Comment by sharkAndshark** [comment]
Allow something like: properties: *?

**Comment by gtitov** [comment]
I'll take a look but not very quickly

**Comment by nyurik** [comment]
@gtitov it shouldn't be too difficult, and I am here to help guide this process and answer questions.

@sharkAndshark currently the `properties:` is a required field in the `postgres.tables.<table_id>` config.  I think a much cleaner approach would be to make properties as optional -- so if they are not set, they are discovered automatically.  This should be a very easy change to make

**Comment by sharkAndshark** [comment]
Maybe add `buffer` and `clip_geom` under  `auto_publish` also?

**Comment by nyurik** [comment]
Sure, we can also do that, but these things are not mutually exclusive
