### ISSUE TITLE
Improve development.md

### ISSUE THREAD

**Issue by sharkAndshark** [urbica/martin#888]
I'm trying to code on my new laptop and I can't build and test martin with just by following the `development.md` directly. Maybe we could update this [shell](https://github.com/maplibre/martin/blob/2bef7c0e4b0b056848e7302c8dedff92bb7b102f/docs/src/development.md?plain=1#L20) like this
```shell
# For Ubuntu-based distros
sudo apt install -y  docker.io  docker-compose  libssl-dev  build-essential  jq  pkg-config  file
```

**Comment by nyurik** [comment]
thx, fixed
