### ISSUE TITLE
Martin leaks database password in logs

### ISSUE THREAD

**Issue by Volatus** [urbica/martin#902]
Currently martin will log the entire connection string at `INFO` level and this includes the provided database password.

**Comment by sharkAndshark** [comment]
Thx!   @Volatus 
Martin print the connection string due to the [code in pool.rs here](https://github.com/maplibre/martin/blob/faa707e0771fbae8cc7993ceb4c589a7e37078be/martin/src/pg/pool.rs#L31).  
Maybe we could only print the database info only instead? @nyurik

**Comment by nyurik** [comment]
In an ideal case, we should parse the connection string, replace password with `"*******"`, and print the resulting string.  The simpler (but possibly buggy) solution would be to use regex similar to what i do in https://github.com/maplibre/martin/blob/faa707e0771fbae8cc7993ceb4c589a7e37078be/martin/src/pg/tls.rs#L32 

Perhaps implement a `fn obfuscate_password(conn_str: &str) -> Cow<'_, str>` which will either return the original `conn_str` if there is no password, or returns an owned string that replaces the password with astriks.
