### ISSUE TITLE
Can Martin Provide BaseMaps itself?

### ISSUE THREAD

**Issue by yekanchi** [urbica/martin#912]
in the martin demo I saw it uses `BaseMaps`.
can martin technically also be used instead of the `BaseMaps`?

**Comment by nyurik** [comment]
I am not certain what you mean by basemap. Usually, your client (e.g. your browser with MapLibre GL JS) gets map tiles from some source.  Those tiles could represent the "base" (oceans/rivers/streets/buildings/...), or some other data like school districts with their ratings.  Martin **could** be the source of those tiles, e.g. from an `.mbtiles` or `.pmfiles` or dynaically computed tiles from a Postgres DB.

That said, Martin is just a software - it does not have any data source. MapLibre at the moment has a rule of not providing any data, but rather focus on software.
