### ISSUE TITLE
Fix cargo publish warning about README

### ISSUE THREAD

**Issue by nyurik** [urbica/martin#914]
When running `cargo publish -p martin`, it shows this warning:

<code>warning: readme `../README.md` appears to be a path outside of the package, but there is already a file named `README.md` in the root of the package. The archived crate will contain the copy in the root of the package. Update the readme to point to the path relative to the root of the package to remove this warning.</code>

**Comment by DarhkVoyd** [comment]
@nyurik  I'm eager to help with this, so please let me know how I can get started. Thanks!

**Comment by nyurik** [comment]
Hi @DarhkVoyd, welcome! Try running `cargo publish -p martin` for a few seconds, and hit `Ctrl+C` the moment it starts compiling. This way it won't try to publish anything.  The above readme warning is shown first, so when you fix it, it will stop being shown.

**Comment by DarhkVoyd** [comment]
@nyurik Hey could you help me out a little, I tried quite a few ways to fix and debug this issue but was unable. I believe this issue is related to an issue within cargo: [check here](https://github.com/rust-lang/cargo/issues/12127)

**Comment by nyurik** [comment]
hmm, it seems like that issue was fixed, and they even have [a test](https://github.com/rust-lang/cargo/pull/12135/files) that sets up something similar to what we have, don't we?   Looking at [crates.io/martin](https://crates.io/crates/martin), [crates.io/martin-mbtiles](https://crates.io/crates/martin-mbtiles), and [crates.io/martin-tile-utils](https://crates.io/crates/martin-tile-utils) - they all have the correct readme showing... So we just need to hide the warning, but even that is fairly low priority - if you want, there are other good tasks like #918 to improve the docs, or many other with the `help wanted` sign :)

**Comment by DarhkVoyd** [comment]
@nyurik I think I was able to hide the warning by manually setting `readme = "README.md"` instead of `readme.workspace = true`. Should I create a PR?

**Comment by nyurik** [comment]
I think this might be another bug with Cargo - maybe file a bug with them, possibly even with a unit test?

The `project()` (`ProjectBuilder`) actually has a [symlink](https://github.com/rust-lang/cargo/blob/d74bc471b9b0be7540d7c9b70eb46b9811197137/crates/cargo-test-support/src/lib.rs#L255) -- so you can add another test, e.g. `fn workspace_symlink_readme()`, with what we have here:

workspace with readme
a project with a symlink readme linking to the workspace readme
everything else is the same as the other tests

P.S. the current tests are [here](https://github.com/rust-lang/cargo/blob/637ade0e6a87c84f5cda2633ae659cac8b3c0283/tests/testsuite/package.rs#L2581)

**Comment by nyurik** [comment]
@DarhkVoyd hi, have you by any chance followed up with the Cargo team?  If not, I will create a ticket for them

**Comment by DarhkVoyd** [comment]
@nyurik Hey, I didn't follow up with the Cargo team. Please feel free to create a ticket.

**Comment by nyurik** [comment]
after writing a bunch of tests and doing other insane things, it seems your solution is still the best - yes, just create a PR setting `martin/cargo.toml`'s to `readme="README.md"` :)

**Comment by DarhkVoyd** [comment]
@nyurik I have created a PR as you asked, kindly review.
