### ISSUE TITLE
Document MBTiles schema as a separate book page

### ISSUE THREAD

**Issue by nyurik** [urbica/martin#918]
We currently have a single [tools page](https://maplibre.org/martin/tools.html) that contains both the description of the `mbtiles` tool, as well as some documentation for the mbtiles schema extensions we support (e.g. hash validation and the well defined normalized/non-normalized/... formats).

I think we should split-up the tools page - to create a documentation section for mbtiles, that has a page documenting schema variants, the hashing capabilities, and another page documenting some capabilities of the `mbtiles` tools

**Comment by sharkAndshark** [comment]
Is it like? @nyurik 
```md
- [MBTiles](50-mbtiles.md)
  - [Supported schemas](51-supported-schemas.md)
  - [Tools](52-tools.md)
```

**Comment by nyurik** [comment]
I think tools (CLI) docs should go first, so maybe name them `51-mbtiles-cli`, `52-mbtiles-schemas` ?  But yes, that's the general approach, thx!
