### ISSUE TITLE
Map Tile API Not working [Question]

### ISSUE THREAD

**Issue by tmoust** [urbica/martin#936]
I successfully set up the Martin Tile Service with my PostgreSQL GIS tables and can access the /catalog and /{sourceID} APIs. 

However, when I request "{sourceID}/{z}/{x}/{y}.pbf," I'm encountering an error: "**Can't parse '1.pbf' as a u32**".

I'm using the default Martin Docker configuration without any additional changes.

Any suggestion? Did I miss any configurations

**Comment by sharkAndshark** [comment]
Hi @tmoust 
Based on the [doc](https://github.com/maplibre/martin/blob/main/README.md#api), there is no `.extension` in the API. You could try `/{sourceID}/{z}/{x}/{y} `.


| URL                                    | Description                                   |
|----------------------------------------|-----------------------------------------------|
| `/`                                    | Status text, that will eventually show web UI |
| `/catalog`                             | List of all sources                           |
| `/{sourceID}`                          | Source TileJSON                               |
| `/{sourceID}/{z}/{x}/{y}`              | Map Tiles                                     |
| `/{source1},...,{sourceN}`             | Composite Source TileJSON                     |
| `/{source1},...,{sourceN}/{z}/{x}/{y}` | Composite Source Tiles                        |
| `/sprite/{spriteID}[@2x].{json,png}`   | Sprites (low and high DPI, index/png)         |
| `/health`                              | Martin server health check: returns 200 `OK`  |

**Comment by nyurik** [comment]
I wonder how common this mistake is... I do not want to add extensions to the tile source tbh.  Adding it would appear as if the user can request different extensions (tile types) from the same source.  E.g. a user can ask for `.pbf` or `.jpg` from the source, expecting it to be rendered in case of jpg or png.  Also, I wouldn't want two different URLs to produce the same result - as this would result in CDN cache misses.

Once we add server-side rendering, this could be done (in theory), but then we would need to supply the style as well, so it will be `/{source}/{style}/{z}/{x}/{y}` or possibly even `/render/{source}/{style}/{z}/{x}/{y}` to differentiate from all other request types.
