### ISSUE TITLE
Consolidate or not the catalog data for sources, sprites, ...

### ISSUE THREAD

**Issue by nyurik** [urbica/martin#949]
Currently, `/catalog` only includes the `tiles` sources. The list of available sprites is not published. The fonts implemented in #755 is currently done as `/fonts` catalog, which also shouldn't be separated.

We can go two routes:
* the consolidated route, where all types of metadata (tile sources, sprites, fonts, ...) are only listed in the `/catalog` endpoint.  The catalog endpoint already has capacity to support it because all tile sources are published as `{ "tiles": [ ... ] }` -- so adding more is easy.
* publish each type of resource at a different endpoint, e.g. `/catalog` will have tile sources, `/sprite` will have the sprites, `/font` will have the fonts. The actual resource can then be retrieved via `/sprite/{name}.png` or `/font/{name}/{range}.pbf` or similar.

I think the first route is more concise, as it will consolidate all types of information including the yet to be discovered one like availability of the style editor, some monitoring services, ... - and will help with discovery of new available stuff by the enduser developers.

**Comment by sharkAndshark** [comment]
I prefer the first route
