### ISSUE TITLE
Document improvement

### ISSUE THREAD

**Issue by sharkAndshark** [urbica/martin#962]
I noticed that there is a level gap between the title and child title in [sources-sprites.md](https://github.com/maplibre/martin/blob/main/docs/src/sources-sprites.md). It jumps from level 1 to level 3.

```text
# Sprite Sources
...
### API
```
* The  level of `Sprite Sources` should be 1 or 2?  2 better?
* The level of `API` should be 2 or 3? 3 better?
* Other document file should be checked either

**Comment by nyurik** [comment]
Sure, if it will look better, go for it :)

**Comment by sharkAndshark** [comment]
Also, how about rename the document markdown files like `ch-00-00-introduction.md`, `ch-01-00-running.md`(just like [rust book](https://github.com/rust-lang/book/tree/main/src)) for a better order in editor.  So contributors could find target file easily.  @nyurik

**Comment by nyurik** [comment]
sure, but our book is not that big - perhaps two digits is enough?  First digit would be top level, second digits is the second level. The rest i would keep as is.  So we can rename them all to `NN-<name-as-it-is-now>`.  Also note that each `N` can be `0..Z` - 36 values (0123456789ABCD...)
