### ISSUE TITLE
Add tile statistics to `mbtiles`, e.g. bbox, number of tiles, ...

### ISSUE THREAD

**Issue by nyurik** [urbica/martin#964]
`mbtiles` currently has `meta-all` to show the content of the metadata table. In addition to that, we should have a feature, either a new command like `stats`, or just expand `meta-all` (less favored) to compute the following:
* compute rough bbox based on the available tiles - i.e. compute min/max X and Y for tile index, and convert it into a bbox. It should be able to update the metadata table with the new value
* compute the number of the tiles in the mbtiles, with the breakdown by zoom level

## Example

```shell
> mbtiles stats myfile.mbtiles
```
#### File Info

File: myfile.mbtiles
Structure: normalized-with-hash
Page size: 4,096B
File size: 34,000KB
... some other useful information about tables/indexes, possibly taking some ideas from `sqlite3_analyzer` utility (I wonder if any of this data is available via standard SQL... if not, we shouldn't show it - no hacks)

#### Tile Info
| zoom | count | smallest | largest | average | bbox |
|---|---|---|---|---|---|
| 0 | 1 | 48KB | 48KB | 48KB | -180,-86,180,86 |
| 1 | 4 | 30KB | 50KB | 38KB | -180,-86,180,86 |
| 2 | 25 | 10KB | 70KB | 15KB | -180,-86,180,86 |
|---|---|---|---|---|---|
| all | 7,247 | 15B | 2.3MB | 50KB | -180,-86,180,86 |

**Comment by sharkAndshark** [comment]
May I take this issue and get your help if needed? @nyurik

**Comment by nyurik** [comment]
Sure, should be fairly straightforward :)

**Comment by nyurik** [comment]
i updated the example output, just to give some rough expectations
